### ISSUE TITLE
CI: Flaky tests

### ISSUE THREAD

**Issue by samuel-w** [borgbase/vorta#632] opened 2020-09-08 17:16 UTC
Tests sometimes fail without any bad code, examples:
https://github.com/borgbase/vorta/pull/631/checks?check_run_id=1086248541
https://github.com/borgbase/vorta/pull/540/checks?check_run_id=1079839809
https://github.com/borgbase/vorta/pull/628/checks?check_run_id=1085059935
https://github.com/borgbase/vorta/pull/607/checks?check_run_id=1087127941
https://github.com/borgbase/vorta/pull/607/checks?check_run_id=1087128002

Since we can run the tests again, its just annoying.
`git commit --allow-empty -m "Make tests go brrrrr"`

Maybe fix with [pytest-xdist](https://pypi.org/project/pytest-xdist/) and upping timeouts?

Edit:
https://github.com/borgbase/vorta/runs/1203963170

**Comment by m3nu** [comment] 2020-09-09 00:20
It's always macOS machines failing. Sometimes there are errors regarding the GUI and then it's very slow. The limit for macOS is also more strict for Github workflows.

I will

- increase the time a bit
- Limit tests on macOS to only Python 3.7

**Comment by samuel-w** [comment] 2020-09-09 01:09
Some failures are database related though:
https://github.com/borgbase/vorta/pull/635/checks?check_run_id=1088827625

**Comment by m3nu** [comment] 2020-09-09 01:18
You're correct. I noticed that before, but it got more frequent recently.

This looks like a race condition, where our BorgThread tries to save a log, while the next test already started and the said table is deleted. I'll look into this again. Just hard to reproduce.

**Comment by samuel-w** [comment] 2020-09-12 22:54
Could just add a gap in between tests https://stackoverflow.com/questions/47770037/interval-between-tests-in-pytest

**Comment by m3nu** [comment] 2020-09-13 00:50
I think the cleaner way is to ensure no background threads are running at the end of the test.

**Comment by m3nu** [comment] 2020-09-13 03:09
See my PR to cancel background threads after each test. I ran this 11x and didn't encounter a false positive test failure.

Let me know how you find that PR.

```
10:30 - ok
10:32 - ok
10:35 - ok
10:40 - ok
10:43 - ok
10:47 - ok
10:51 - ok
10:56 - ok
11:00 - ok
11:04 - 
```

**Comment by m3nu** [comment] 2020-09-13 05:09
Leave this open, since there are other unreliable tests left.

**Comment by m3nu** [comment] 2021-02-15 07:19
Closing in favor of more detailed discussion on same topic: #748

**Closed by m3nu** 2021-02-15 07:19 UTC
Labels: priority:low, type:task
