### ISSUE TITLE
Vorta partially broken on Plasma Desktop

### ISSUE THREAD

**Issue by sbaragnaus2** [borgbase/vorta#763] opened 2021-01-17 17:20 UTC
**Describe the bug**
Vorta doesn't work anymore on Plasma Desktop (Kde). You can't anymore select a single folder because _**open**_ button doesn't work. So you can't **add a new local repository,** you can't **reconnect a local repository,** you can't **add new folder to backup,** you can't **restore** or **mount a backup**. This happens in three of my systems (**Fedora 33 Kde**, **Manjaro**, **Solus Plasma**). Instead **Vorta works** on **Gnome** (tested on Fedora 33 Gnome). 

**To Reproduce**
1. Go to 'sources'
2. Click on 'add folder'
3. Scroll down to '_folder you want to include in your backup_, then click open'
4. Button doesn't work (_see below_)
![2021-01-17_17-27](https://user-images.githubusercontent.com/16922051/104850160-c45f3780-58ed-11eb-9601-e8d54f43e8ea.png)

**To Reproduce (alternative)**
1. Go to 'repository'
2. Click on 'choose a local path as repository'
3. Scroll down to '_folder you want to select as your repository_, then click open'
4. Button doesn't work (_see below_)
![2021-01-17_17-29](https://user-images.githubusercontent.com/16922051/104850238-3041a000-58ee-11eb-9956-3e7fd114b513.png)

Same happens if you click **mount** or **extract**.

**Desktop:**
**System 1**
- Operating System: Fedora 33
- KDE Plasma Version: 5.20.5
- KDE Frameworks Version: 5.78.0
- Qt Version: 5.15.2
- Vorta version: 0.7.1
- Installed from: Flathub (Flatpak)

**System 2**
- Operating System: Manjaro Linux
- KDE Plasma Version: 5.20.4
- KDE Frameworks Version: 5.77.0
- Qt Version: 5.15.2
- Vorta version: 0.7.1
- Installed from: Flathub (Flatpak)

**System 3**
- Operating System: Solus 4.1
- KDE Plasma Version: 5.20.5
- KDE Frameworks Version: 5.78.0
- Qt Version: 5.15.2
- Vorta version: 0.7.1 / Borg version 1.1.14
- Installed from: Official Solus repository

**Additional context**
-

I think this is an important bug. Please fix it. Thanks.

**Comment by samuel-w** [comment] 2021-01-17 19:05
Duplicate of #693, closing.

**Closed by samuel-w** 2021-01-17 19:05 UTC
