### ISSUE TITLE
Compression method gets reset to lz4 on restart

### ISSUE THREAD

**Issue by RubenKelevra** [borgbase/vorta#1555] opened 2023-01-20 17:05 UTC
### Description

If Vorta gets restarted, it will reset the compression method to lz4.

[Screencast from 2023-01-20 18-01-52.webm](https://user-images.githubusercontent.com/614929/213760113-8e5a7665-c472-4243-9a79-35cdb4850760.webm)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

ArchLinux latest

### Version of Vorta

0.8.9

### What did you install Vorta with?

Other

### Version of Borg

1.2.3

**Comment by real-yfprojects** [comment] 2023-01-20 19:44
Duplicate of #1495.

**Closed by real-yfprojects** 2023-01-20 19:44 UTC
