### ISSUE TITLE
borg binary not found

### ISSUE THREAD

**Issue by stderr-to-devnull** [borgbase/vorta#367] opened 2019-10-14 11:22 UTC
kubuntu 19.04, after new vorta flatpak update to 0.6.23: scheduled tasks fail because borg binary cannot be found

* How to fix this? Checked FAQs, guide, nothing
* Why is there no option to specify the system installed binary instead?

**Comment by Hofer-Julian** [comment] 2019-10-14 11:33
That is an interesting problem.
How do you get the idea that "the borg binary is not found"?

Regarding your question: It would be counterproductive to use the system borg in a sandboxed flatpak.

**Comment by stderr-to-devnull** [comment] 2019-10-14 11:35
Hi Julian,

Scheduled vorta backups fails with this error in the notification area
So I found borg binary in these locations:
```/var/lib/flatpak/app/com.borgbase.Vorta/current/active/files/bin
/var/lib/flatpak/app/com.borgbase.Vorta/x86_64/stable/active/files/bin```
Reported borg version by Vorta in misc tab is 1.1.10 in /app/bin/borg

I also tried pruning some backups, nothing happens. This worked fine until today

**Comment by stderr-to-devnull** [comment] 2019-10-14 11:39
I just saw now that Vorta reports v 0.6.22, even after I ran flatpak update:

`Description                                                                   Application                         Version Branch Arch   Origin  Installation
Vorta - Backup client                                                         com.borgbase.Vorta                  v0.6.23 stable x86_64 flathub system`
`flatpak update com.borgbase.Vorta
Looking for updates…


        ID                                           Arch              Branch           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264            x86_64            19.08            flathub           594,2 kB / 593,4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.`

**Comment by Hofer-Julian** [comment] 2019-10-14 12:03
You could try to remove vorta, run flatpak update and then install vorta again.

**Comment by stderr-to-devnull** [comment] 2019-10-15 08:37
I just did that, nothing changed, when I run Vorta and press `Start Backup` I get "Borg binary not found"

**Comment by Hofer-Julian** [comment] 2019-10-15 18:01
Unfortunately I cannot reproduce your error. As flatpak eliminates to a high degree the influence of a different OS and DE (in my case GNOME and Fedora), I have to suspect that something is broken with your flatpak installation. I will keep this issue open in case someone else has a similar problem.

Currently, i can only advise you to install Vorta via pip until the underlying problem is found.

**Comment by stderr-to-devnull** [comment] 2019-10-16 08:23
If I install from pip, do I need to remake the config? If I take current config from `var` in my home dir, will it work?

Though I would try to understand why Vorta gives this "binary not found" message, I mentioned above where I found the binary in the Vorta flatpak app dir, are those 2 paths correct? Where should the binary be to resolve the issue?

**Comment by Hofer-Julian** [comment] 2019-10-16 09:39
Yes, that will work.

**Comment by stderr-to-devnull** [comment] 2019-10-16 14:45
> Though I would try to understand why Vorta gives this "binary not found" message, I mentioned above where I found the binary in the Vorta flatpak app dir, are those 2 paths correct? Where should the binary be to resolve the issue?

Can you help with this info please?

**Comment by m3nu** [comment] 2019-10-17 00:15
I added a new label "support".  Issues are to discuss features and bugs. Support could be done in the chat if anyone is there.

Hope you get it working @stderr-to-devnull , but closing this now. Not even sure this is Vorta-related.

**Closed by m3nu** 2019-10-17 00:15 UTC
Labels: type:support
