### ISSUE TITLE
Vorta don't save the Compression Setting

### ISSUE THREAD

**Issue by Revan335** [borgbase/vorta#1562] opened 2023-01-21 14:14 UTC
### Description

Hello,

Vorta don't save the Compression Setting.
Change the Compression from LZ4 to for example Zstandard Level 8 (modern) and click to Backup started. This finished.
Closed the Vorta Client und restarted, the Compression is of LZ4 again.
Other Settings Changes are saved. For example Start Vorta Main Window by start under Misc Tab.

The Installation is from the AUR: http://aur.archlinux.org/packages/vorta

Many Thanks!

Greetings!

Revan335

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Manjaro GNOME

### Version of Vorta

0.8.9

### What did you install Vorta with?

Other

### Version of Borg

1.2.2

### Logs

```pytb
No Log Entry for the Change Compression or other Settings. Only for the Start of the Vorta Client or the Running Backup.
```

**Comment by real-yfprojects** [comment] 2023-01-21 15:43
Duplicate of #1495.

**Closed by real-yfprojects** 2023-01-21 15:43 UTC
