### ISSUE TITLE
Fatal error (vorta/application.py, line 186: AttributeError: 'NoneType' object has no attribute 'id')

### ISSUE THREAD

**Issue by jaysonwcs** [borgbase/vorta#1295] opened 2022-05-12 12:15 UTC
**Describe the bug**
Exception message displayed as soon as the system boots up and Vorta is initialized.

**To Reproduce**
1. Message shown as soon as system boots up and Vorta is started.

**Environment (please complete the following information):**
- OS: Arch Linux (Linux Desktop 5.17.5-arch1-2  # 1  SMP PREEMPT Fri, 06 May 2022 18:29:03 +0000 x86_64 GNU/Linux)
- Vorta version: 0.8.4 (Borg: 1.2.0)
- Installed from: AUR

**Additional context**
Log:

```
2022-05-12 08:55:25,688 - vorta.i18n - DEBUG - Loading translation failed for ['pt', 'pt-BR', 'pt-Latn-BR'].
2022-05-12 08:55:25,882 - vorta.views.source_tab - DEBUG - Added item number 0 from 1
2022-05-12 08:55:25,882 - vorta.views.source_tab - DEBUG - Added item number 1 from 2
2022-05-12 08:55:26,072 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2022-05-12 08:55:26,204 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2022-05-12 08:55:26,204 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2022-05-12 08:55:26,211 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2022-05-12 08:55:26,635 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2022-05-12 08:55:26,635 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-05-12 08:55:26,635 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2022-05-12 08:55:26,639 - vorta.scheduler - INFO - Setting timer for profile 1
2022-05-12 08:55:26,640 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 09:52:46.781226
2022-05-12 08:55:26,644 - vorta.scheduler - INFO - Setting timer for profile 2
2022-05-12 08:55:26,645 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:13.255314
2022-05-12 08:55:26,648 - vorta.scheduler - INFO - Setting timer for profile 6
2022-05-12 08:55:26,649 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:12.296414
2022-05-12 08:55:26,653 - vorta.scheduler - INFO - Setting timer for profile 7
2022-05-12 08:55:26,654 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:12.311881
2022-05-12 08:55:26,658 - vorta.scheduler - INFO - Setting timer for profile 8
2022-05-12 08:55:26,659 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:54.263485
2022-05-12 08:55:26,662 - vorta.scheduler - INFO - Setting timer for profile 9
2022-05-12 08:55:26,663 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:02.630720
2022-05-12 08:55:26,666 - vorta.scheduler - DEBUG - Nothing scheduled for profile 10 because of unset repo.
2022-05-12 08:55:26,666 - vorta.scheduler - INFO - Setting timer for profile 10
2022-05-12 08:55:26,667 - vorta.scheduler - DEBUG - Catching up by running job for Android Borgbase (10)
2022-05-12 08:55:26,669 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/application.py", line 186, in set_borg_details_result
    self.scheduler.reload_all_timers()  # Start timer after Borg version is set.
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 177, in reload_all_timers
    self.set_timer_for_profile(profile.id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 127, in set_timer_for_profile
    self.create_backup(profile_id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 212, in create_backup
    if self.app.jobs_manager.is_worker_running(site=profile.repo.id):
AttributeError: 'NoneType' object has no attribute 'id'
2022-05-12 09:10:25,150 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-05-12 09:10:25,163 - vorta.scheduler - INFO - Setting timer for profile 1
2022-05-12 09:10:25,166 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 09:52:46.781227
2022-05-12 09:10:25,178 - vorta.scheduler - INFO - Setting timer for profile 2
2022-05-12 09:10:25,181 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:13.255314
2022-05-12 09:10:25,191 - vorta.scheduler - INFO - Setting timer for profile 6
2022-05-12 09:10:25,194 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:12.296414
2022-05-12 09:10:25,205 - vorta.scheduler - INFO - Setting timer for profile 7
2022-05-12 09:10:25,208 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:12.311881
2022-05-12 09:10:25,218 - vorta.scheduler - INFO - Setting timer for profile 8
2022-05-12 09:10:25,221 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:54.263485
2022-05-12 09:10:25,231 - vorta.scheduler - INFO - Setting timer for profile 9
2022-05-12 09:10:25,233 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-12 18:00:02.630720
2022-05-12 09:10:25,240 - vorta.scheduler - DEBUG - Nothing scheduled for profile 10 because of unset repo.
2022-05-12 09:10:25,240 - vorta.scheduler - INFO - Setting timer for profile 10
2022-05-12 09:10:25,242 - vorta.scheduler - DEBUG - Catching up by running job for Android Borgbase (10)
2022-05-12 09:10:25,244 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 177, in reload_all_timers
    self.set_timer_for_profile(profile.id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 127, in set_timer_for_profile
    self.create_backup(profile_id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 212, in create_backup
    if self.app.jobs_manager.is_worker_running(site=profile.repo.id):
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by real-yfprojects** [comment] 2022-05-12 18:25
Duplicate of #1286.

**Closed** 2022-05-12 18:26 UTC
Labels: status:duplicate
