### ISSUE TITLE
I got an validating expression error

### ISSUE THREAD

**Issue by amiroslaw** [borgbase/vorta#101] opened 2018-12-24 14:30 UTC
I can't open the app. I got "Error validating expression '*/48': the step value (48) is higher than the total range of the expression (23)", when I set up schedule to 48 hours. 

```bash
Traceback (most recent call last):
  File "/usr/bin/vorta", line 11, in <module>
    load_entry_point('vorta==0.6.2', 'gui_scripts', 'vorta')()
  File "/usr/lib/python3.7/site-packages/vorta/__main__.py", line 35, in main
    app = VortaApp(sys.argv, single_app=True)
  File "/usr/lib/python3.7/site-packages/vorta/application.py", line 47, in __init__
    self.scheduler = VortaScheduler(self)
  File "/usr/lib/python3.7/site-packages/vorta/scheduler.py", line 21, in __init__
    self.reload()
  File "/usr/lib/python3.7/site-packages/vorta/scheduler.py", line 29, in reload
    minute=profile.schedule_interval_minutes)
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/__init__.py", line 82, in __init__
    field = field_class(field_name, exprs, is_default)
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/fields.py", line 33, in __init__
    self.compile_expressions(exprs)
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/fields.py", line 58, in compile_expressions
    self.compile_expression(expr)
  File "/usr/lib/python3.7/site-packages/apscheduler/triggers/cron/fields.py", line 70, in compile_expression
    six.raise_from(exc, None)
  File "<string>", line 3, in raise_from
```
How to change the configuration now if I can't open the program and how can I schedule backups to have one per week?

**Desktop:**
 - OS: Manjaro i3 18.0.1 release
- vorta 0.6.2-1

**Comment by m3nu** [comment] 2018-12-25 02:55
That's a valid concern and I can reproduce it. Currently only numbers from 0-23 will work, since this field is passed to the cron-like scheduler. For multiple days, we need a day-field, which is not a problem.

To fix your settings, you'd have to edit the sqlite file. Table `backupprofilemodel`. Or email it to hello[at]borgbase.com and I'll change it for you and return it.

`/home/USERNAME/.local/share/Vorrta` (paths for other OSs [here](https://github.com/ActiveState/appdirs#some-example-output))

<img width="1276" alt="screenshot 2018-12-25 at 10 52 19" src="https://user-images.githubusercontent.com/3916435/50410342-5097f100-0833-11e9-9618-e25b028ca0d5.png">

**Comment by m3nu** [comment] 2018-12-25 02:57
Tasks:

- [x] Limit allowed hours to 23.
- [ ] Add day-field to scheduler.

**Comment by m3nu** [comment] 2018-12-25 04:39
Pushed the fix for this. Will release in the next days after fixing a few more small bugs we found. So you could wait with editing the settings DB directly.

**Closed** 2018-12-25 05:06 UTC
Labels: type:bug, type:enhancement
