### ISSUE TITLE
Vorta hangs on backup creation

### ISSUE THREAD

**Issue by artemislena** [borgbase/vorta#1359] opened 2022-06-17 09:10 UTC
**Describe the bug**
L: Vorta starts hanging on backup creation at some point, e.g. it's almost finished, but then just stops on backup creation, usually on a file that was modified (at least the last file it displays usually has an `(M)` behind it), after about 14k files of about 16k. Meanwhile, `borg create` just seems to work?
```
artemis@ArtemisBook ~ % borg create --debug --exclude-from excludefile --rsh 'ssh -i ~/.ssh/borg' 'ssh://artemis-mba-m1@192.168.100.22:2222/./::artemis-2022-06-17-110400' /Users/artemis
using builtin fallback logging configuration
33 self tests completed in 0.04 seconds
SSH command line: ['ssh', '-i', '~/.ssh/borg', '-p', '2222', 'artemis-mba-m1@192.168.100.22', 'borg', 'serve', '--debug']
Remote: using builtin fallback logging configuration
Remote: 33 self tests completed in 0.40 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'/./'
Remote: Resolved repository path to '/var/lib/borgbackup/artemis-mba-m1'
Remote: Verified integrity of /var/lib/borgbackup/artemis-mba-m1/index.57
Enter passphrase for key ssh://artemis-mba-m1@192.168.100.22:2222/./: 
TAM-verified manifest
security: read previous location 'ssh://artemis-mba-m1@192.168.100.22:2222/./'
security: read manifest timestamp '2022-06-17T09:03:27.175785'
security: determined newest manifest timestamp as 2022-06-17T09:03:27.175785
security: repository checks ok, allowing access
Creating archive at "ssh://artemis-mba-m1@192.168.100.22:2222/./::artemis-2022-06-17-110400"
Verified integrity of /Users/artemis/.cache/borg/131277e388630ec8b4b28407cc11fcd9c83058e1394dc74fc2c6fced3f000ef4/chunks
Reading files cache ...
Verified integrity of /Users/artemis/.cache/borg/131277e388630ec8b4b28407cc11fcd9c83058e1394dc74fc2c6fced3f000ef4/files
security: read previous location 'ssh://artemis-mba-m1@192.168.100.22:2222/./'
security: read manifest timestamp '2022-06-17T09:03:27.175785'
security: determined newest manifest timestamp as 2022-06-17T09:03:27.175785
security: repository checks ok, allowing access
Processing files ...
Remote: Cleaned up 0 uncommitted segment files (== everything after segment 57).
Remote: Verified integrity of /var/lib/borgbackup/artemis-mba-m1/hints.57
/Users/artemis/Library/Group Containers/group.com.apple.secure-control-center-preferences/Library/Preferences/group.com.apple.secure-control-center-preferences.av.plist: open: [Errno 13] Permission denied: 'group.com.apple.secure-control-center-preferences.av.plist'
Remote: check_free_space: required bytes 550507868, free bytes 2881809608704
security: saving state for 131277e388630ec8b4b28407cc11fcd9c83058e1394dc74fc2c6fced3f000ef4 to /Users/artemis/.config/borg/security/131277e388630ec8b4b28407cc11fcd9c83058e1394dc74fc2c6fced3f000ef4
security: current location   ssh://artemis-mba-m1@192.168.100.22:2222/./
security: key type           5
security: manifest timestamp 2022-06-17T09:04:30.141622
RemoteRepository: 1.84 MB bytes sent, 4.82 kB bytes received, 23 messages sent
```

**To Reproduce**
1. Initialize a new repository
2. Create a backup (preferably with lots of files in it, haven't tried with less)
3. Wait. Forever.

**Environment (please complete the following information):**
- OS: macOS
- Vorta version: 0.8.6 (Borg 1.2.1)
- Installed from: Homebrew

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by m3nu** [comment] 2022-06-17 10:00
Please use the latest version 0.8.7.

Duplicate of https://github.com/borgbase/vorta/issues/1356

**Closed by m3nu** 2022-06-17 10:00 UTC
