### ISSUE TITLE
Vorta pour Borg

### ISSUE THREAD

**Issue by DominiqueFrt** [borgbase/vorta#1232] opened 2022-03-24 09:17 UTC
`Erreur non prise en charge, veuillez remplir un rapport de bug avec ce texte à l'adresse suivante
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/application.py", line 124, in create_backup_action
    msg = BorgCreateJob.prepare(profile)
  File "/app/lib/python3.7/site-packages/vorta/borg/create.py", line 74, in prepare
    ret = super().prepare(profile)
  File "/app/lib/python3.7/site-packages/vorta/borg/borg_job.py", line 151, in prepare
    ret['password'] = cls.keyring.get_password('vorta-repo', profile.repo.url)
  File "/app/lib/python3.7/site-packages/vorta/keyring/secretstorage.py", line 42, in get_password
    return items[0].get_secret().decode("utf-8")
  File "/app/lib/python3.7/site-packages/secretstorage/item.py", line 96, in get_secret
    self.ensure_not_locked()
  File "/app/lib/python3.7/site-packages/secretstorage/item.py", line 48, in ensure_not_locked
    raise LockedException('Item is locked!')
secretstorage.exceptions.LockedException: Item is locked!`

![KeePassXC](https://user-images.githubusercontent.com/42612895/159883222-4938c902-4b16-4955-9332-cf2522fe39d1.png)

**Comment by real-yfprojects** [comment] 2022-03-24 16:55
Probably duplicate of  #1233.

**Comment by DominiqueFrt** [comment] 2022-03-24 18:21
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-37-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-2700K CPU @ 3.50GHz
Memory: 15.6 Gio of RAM
Graphics Processor: NVIDIA GeForce GT 710/PCIe/SSE

![KeePassXc](https://user-images.githubusercontent.com/42612895/159984387-2b024bce-0159-4e8f-96c2-f79ecc310a4f.png)

![Vorta Création nouveau profil](https://user-images.githubusercontent.com/42612895/159984396-08b8bbbb-a07f-4bca-8f13-d03891123b0c.png)

![usr_bin_gnome-keyring-daemon](https://user-images.githubusercontent.com/42612895/159984401-ebd706bd-1253-4c80-a029-555b585bbde3.png)

![usr_bin_kwalletd5](https://user-images.githubusercontent.com/42612895/159984406-3f0b37ad-6d1a-4cdd-a033-2df9b3280a9a.png)
2

**Comment by real-yfprojects** [comment] 2022-03-24 19:18
> ![usr_bin_gnome-keyring-daemon](https://user-images.githubusercontent.com/42612895/159984401-ebd706bd-1253-4c80-a029-555b585bbde3.png)
> 
> ![usr_bin_kwalletd5](https://user-images.githubusercontent.com/42612895/159984406-3f0b37ad-6d1a-4cdd-a033-2df9b3280a9a.png)

These show the permissions of `/usr/bin/gnome-keyring-daemon` and `/usr/bin/kwalletd5` for anyone wondering.

**Comment by real-yfprojects** [comment] 2022-04-09 13:34
Closing in favour of #1233.

**Closed by real-yfprojects** 2022-04-09 13:34 UTC
Labels: status:duplicate
