### ISSUE TITLE
Pre-built binary not starting on latest macOS release

### ISSUE THREAD

**Issue by janszczepanski** [borgbase/vorta#381] opened 2019-11-06 14:55 UTC
When starting I get the following error message:

> "Vorta" cannot be started... This software needs to be updated. Contact the developer for more information.

Homebrew Cask downloaded this file from github.com today at 15:46.

**Comment by m3nu** [comment] 2019-11-06 15:13
I'm not building on the latest macOS version 10.15 yet. Will probably update in 2-3 weeks.

Until then you can just clone this repo and build it yourself with `make Vorta.app`. More info [here](https://vorta.borgbase.com/contributing/).

I'll leave this issue open and update once I've built on 10.15.

**Comment by m3nu** [comment] 2019-11-12 04:37
Hi, I couldn't reproduce this after upgrading to macOS 10.15.1. Running Vorta from either Python directly or from the pre-built `Vorta.app` bundle are both fine.

Usually it's the other way round: new builds don't run on older systems. Still need to test this.

**Comment by adamluk** [comment] 2019-11-15 20:39
I am seeing this as well with macOS 10.15.1, using Vorta.app v0.6.23

> 2019-11-15 20:30:00,093 - vorta.scheduler - ERROR - Conditions for backup not met. Aborting.
> 2019-11-15 20:30:00,093 - vorta.scheduler - ERROR - Borg binary was not found.
> 2019-11-15 20:30:00,094 - vorta.notifications - DEBUG - notification not suppressed
> 

![Screenshot 2019-11-15 at 20 34 46 1](https://user-images.githubusercontent.com/9057461/68974064-b85a8000-07e7-11ea-8e63-b0131c2bdc06.png)
![Screenshot 2019-11-15 at 20 36 14](https://user-images.githubusercontent.com/9057461/68974073-bdb7ca80-07e7-11ea-8bb0-8dc0be01b22b.png)

When I navigate to the directory indeed the binary is not present. Happy to help you troubleshoot this further if need be - let me know what you need. This has only happened since I upgraded to Catalina.

**Comment by m3nu** [comment] 2019-11-16 06:46
I was able to reproduce this error after fully uninstalling Borg and forcing it to use the built-in binary.

The root cause seems to be that macOS blocks the Borg binary and the user needs to add an exception in *Preferences > Security > General*

<img width="595" alt="Screen Shot 2019-11-16 at 13 51 37" src="https://user-images.githubusercontent.com/3916435/68989303-79780900-087f-11ea-8233-8f9474155320.png">

As a workaround it's currently best to install Borg yourself using pip.

Also note that there is a long delay when starting Vorta because macOS seems to validate every single library file every time.

That's all I know for now. I hope we can get this to work better in the future.

**Comment by m3nu** [comment] 2020-05-28 04:23
Should be fixed. That last 2 releases had notarized builds.

**Closed by m3nu** 2020-05-28 04:23 UTC
Labels: status:not-reproducable
