### ISSUE TITLE
Symbol not found: _ffi_closure_alloc

### ISSUE THREAD

**Issue by imichael** [borgbase/vorta#1329] opened 2022-05-25 21:46 UTC
System Version:	macOS 10.14.6 (18G9323)
Kernel Version:	Darwin 18.7.0

Vorta version 0.8.5
Borg Version: 1.2.0

On Schedule page, click Start Backup (also happens with scheduled backup).
Does not happen with Vorta 0.8.2. I think it started with 0.8.4

2022-05-24 02:02:55,712 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "application.py", line 125, in create_backup_action
  File "borg/create.py", line 74, in prepare
  File "borg/borg_job.py", line 152, in prepare
  File "keyring/darwin.py", line 75, in get_password
  File "keyring/darwin.py", line 103, in _resolve_password
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /Applications/Vorta.app/Contents/MacOS/lib-dynload/_ctypes.cpython-39-darwin.so

~> ls -l /usr/lib/libffi.dylib 
-rwxr-xr-x  1 root  wheel  47568 May  4  2019 /usr/lib/libffi.dylib

**Comment by m3nu** [comment] 2022-05-26 02:41
Duplicate of #1305

**Closed by m3nu** 2022-05-26 02:41 UTC
