### ISSUE TITLE
No snapshots listed

### ISSUE THREAD

**Issue by JanSchnacki** [borgbase/vorta#64] opened 2018-11-28 21:56 UTC
After #21 was fixed, I can refresh the snapshots, but unfortunately I do not see my snapshots.

I guess, I configured everything "mostly ok" (since vorta shows me the size information for the repository) but something seems to bother vorta.

I can click "refresh snapshots" and it will run the progress-bar for a while. Then it will say "Refreshing snapshots done.".

The list with the snapshots will remain empty. The "snapshotmodel" table in the settings.db stays empty. The "eventlogmodel" table shows only non-zero returncodes for all "list" runs.

By the way: The "repopassowrd" table in the settings.db is completely empty, too. I guess this should not be the case?

**Comment by ThomasWaldmann** [comment] 2018-11-28 23:03
@m3nu maybe some timeout prematurely terminating the borg command before it has finished?

**Comment by m3nu** [comment] 2018-11-29 00:44
I didn't add any timeouts. Will test it today. I already made a test repo with 200 dummy snapshots.

**Comment by m3nu** [comment] 2018-11-29 00:48
> By the way: The "repopassowrd" table in the settings.db is completely empty, too. I guess this should not be the case?

This table is only used if no native "secure" way to save passwords is available. It will be empty in most cases. So that's fine.

> The list with the snapshots will remain empty. The "snapshotmodel" table in the settings.db stays empty. The "eventlogmodel" table shows only non-zero returncodes for all "list" runs.

I suspect some JSON goes missing on the way and parsing fails. Will try with the large test repo over a slow connection. So far it worked fine for smaller remote repos and large local repos.

**Comment by m3nu** [comment] 2018-11-29 05:43
Just made a test repo with 1600 archives and copied it to BorgBase. Then added it in Vorta. It loaded the archives just fine. They are all in the sqlite DB and the table. I'd still like to get to the bottom of this, @JanSchnacki. So here some other things I can think of:

- Did you see anything unusual in the logs? Locations should be like mentioned [here](https://github.com/m3nu/vorta#debugging-and-bugs).
- Can you share the json file that's produced? You mentioned it's 150kb. That size shouldn't be an issue (the list of my test repo is 500kb). The file listing for some local test repos was 50MB and it still parsed fine.
- What `borg` version is running on the server? You said it's a NAS? Maybe the format changed and a key is missing?
- Is this error only happening for this repo or others as well?

**Comment by JanSchnacki** [comment] 2018-11-30 21:13
Argh...

I'm sorry @m3nu , I just looked in the log and there it says

`2018-11-30 22:04:02,570 - INFO - Running command borg list --info --log-json --json /NasSnake2/jan/Backups/borgbackup/snake2016
2018-11-30 22:04:42,226 - ERROR - passphrase supplied in BORG_PASSPHRASE or by BORG_PASSCOMMAND is incorrect.
2018-11-30 22:04:42,238 - WARNING - 
`
So, I must have mistyped my password (or Vorta has a problem with a "!" in the password, or with a password 20 characters long).

I think, there currently is no way to reset the password for a profile, is that correct? Can I just "unlink" the profile and reconfigure it?

I really should have looked for this logfile earlier. Apart from that: my borg version is 1.1.7

**Comment by m3nu** [comment] 2018-12-02 01:30
Closing this because the issue is due to the missing password, which shouldn't happen under normal circumstances.

**Closed by m3nu** 2018-12-02 01:30 UTC
Labels: type:bug
