### ISSUE TITLE
Crashes with "database is locked" after scheduled backup run

### ISSUE THREAD

**Issue by fantom-x** [borgbase/vorta#1032] opened 2021-07-12 21:03 UTC
**Describe the bug**
Vorta client periodically crashes

**To Reproduce**
I do not have any reproduction steps; the Vorta icon periodically disappears form the task bar. Seems to be happening right after a scheduled backup.

**Environment (please complete the following information):**
- OS: MacOS 11.4 9BigSir)
- Vorta version: 0.7.7
- Borg version: 1.1.16
- Installed from: brew

**Additional context**
```
2021-07-11 21:12:05,215 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg list --info --log-json --json /_Backup/Docs
2021-07-11 21:12:06,188 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "peewee.py", line 3144, in execute_sql
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "borg/borg_thread.py", line 273, in run
  File "borg/list_repo.py", line 43, in process_result
  File "peewee.py", line 6603, in delete_instance
  File "peewee.py", line 1907, in inner
  File "peewee.py", line 1978, in execute
  File "peewee.py", line 2474, in _execute
  File "peewee.py", line 3157, in execute
  File "peewee.py", line 3151, in execute_sql
  File "peewee.py", line 2917, in __exit__
  File "peewee.py", line 190, in reraise
  File "peewee.py", line 3144, in execute_sql
peewee.OperationalError: database is locked



vorta.log:sqlite3.OperationalError: database is locked
vorta.log:peewee.OperationalError: database is locked
vorta.log.2021-07-03:sqlite3.OperationalError: database is locked
vorta.log.2021-07-03:peewee.OperationalError: database is locked
vorta.log.2021-07-03:sqlite3.OperationalError: database is locked
vorta.log.2021-07-03:peewee.OperationalError: database is locked
vorta.log.2021-07-10:sqlite3.OperationalError: database is locked
vorta.log.2021-07-10:peewee.OperationalError: database is locked

```

**Comment by m3nu** [comment] 2021-07-13 05:47
Thanks for letting us know. Don't recall seeing such an error ever before, but will keep an eye on scheduled jobs.

**Comment by m3nu** [comment] 2021-11-06 12:34
Looks like a dupe of #1081, which has more details. So let's resolve it there.

**Closed by m3nu** 2021-11-06 12:34 UTC
Labels: type:bug, os:macos
