### ISSUE TITLE
[Suggestion] Add the repo total size as an extra line in the archive list

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#430] opened 2020-04-01 20:58 UTC
Currently, the total archive (repo) size is not shown on the archive list. I was very puzzled Vorta not showing the total size there.

As explained in https://borgbackup.readthedocs.io/en/stable/usage/info.html , the list command usually show that data, so I 

#### suggest to add the total repo size data in an extra line of the archive output.

![grafik](https://user-images.githubusercontent.com/1151915/78185898-183a8600-746c-11ea-8e11-d9c6da40d460.png)

![grafik](https://user-images.githubusercontent.com/1151915/78185633-ad894a80-746b-11ea-9731-ce363b7043cb.png)

![grafik](https://user-images.githubusercontent.com/1151915/78185681-bb3ed000-746b-11ea-8b2f-89c8b0eb3b10.png)

**Comment by m3nu** [comment] 2020-04-02 03:32
We show the size of the new data there, rather than the total size. I think this makes more sense in the context of a single archive. To see data on the repo globally, you can look on the *Repo* screen.

**Comment by Wikinaut** [comment] 2020-04-02 08:04
Hello, let me explain what the problem underneath your argumentation is.

Here is a typical scenario, why I just set up to explain in a few steps the apparent problem (inconsistency of the display with the actual status). Please take your time and study all my steps.

#### Step 1: Creating a new repo; no archive (= empty archive) Display/list = OK
![20200402-093659 Auswahl](https://user-images.githubusercontent.com/1151915/78223757-b4de4180-74c7-11ea-93d0-596b5b392e95.png)
![20200402-093711 Auswahl](https://user-images.githubusercontent.com/1151915/78223766-b9a2f580-74c7-11ea-9b7b-fc3f714a85aa.png)

#### Step 2: Making a first backup (=adding a frist archive to the repo). Display/list = OK
![20200402-093942 Auswahl](https://user-images.githubusercontent.com/1151915/78223891-e5be7680-74c7-11ea-909a-7658605eb7a3.png)

Picture 3:
![20200402-093951 Auswahl](https://user-images.githubusercontent.com/1151915/78223901-e8b96700-74c7-11ea-8ca6-5e5ac4d630f6.png)

#### Step 3: removing a small amount of original data

#### Step 4: Making a second backup (= adding a second archive). Display/list = OK
![20200402-094027 Auswahl](https://user-images.githubusercontent.com/1151915/78224100-38982e00-74c8-11ea-9b3b-466476e49bb7.png)
![20200402-094037 Auswahl](https://user-images.githubusercontent.com/1151915/78224107-3b931e80-74c8-11ea-9e87-f83ccc35db17.png)

##### Step 5: NOW PRUNING the repo (removing the first backup). Display/list = NOT OK
(compare to Step 2).

![20200402-094121 Auswahl](https://user-images.githubusercontent.com/1151915/78224186-5c5b7400-74c8-11ea-9c0b-069f739e4ce2.png)
![20200402-094130 Auswahl](https://user-images.githubusercontent.com/1151915/78224189-5ebdce00-74c8-11ea-82a1-5f7e81169b9e.png)

#### Result:

*the resulting list of archive(s) does not reflect, not even approximately, the content of the repo. Compare to result of step 2.
* I expect a line with a result similar to the content of picture 3 (see above).

**Comment by m3nu** [comment] 2020-04-07 03:21
I'm aware the the total size is wrong, but the delta size of that archive is still correct. Even if you prune the old archive, the files from the old archive will still stay in the repo. I don't think we can really change that, since the archive list only displays the info we get from Borg.

You suggest taking the size of pruned archives and adding them to the remaining archive.

Again, the size in the archive list only shows the new data added during that run. It won't show stats for the full repo and isn't updated after the first backup run.

**Comment by Wikinaut** [comment] 2020-04-07 09:06
@m3nu you wrote:
>  since the archive list only displays the info we get from Borg.

That's my point:  it will be a big help if you add the ```last line of the Borg list output``` also **inside** the ```Archive``` window, at the last line, and not only on the general ("Repository") page of Vorta like in the example from the documentation:

![grafik](https://user-images.githubusercontent.com/1151915/78650820-bc368e00-78bf-11ea-818a-404706d9b9c3.png)

**Comment by Wikinaut** [comment] 2020-04-07 10:01
Hmmm, perhaps you find a suitable and convincing solution.

**Comment by Golddouble** [comment] 2020-04-30 08:48
Furthermore:
It's also the entry behind "compressed size" in the tab "Repository" that is also wrong after deleting a snapshot.
Maybe at least this could be fixed?

**Comment by Wikinaut** [comment] 2020-05-02 13:12
Vorta:
![grafik](https://user-images.githubusercontent.com/1151915/80865036-ed1f9e00-8c86-11ea-8625-76ee072c9e22.png)

However, on the archive page:
![grafik](https://user-images.githubusercontent.com/1151915/80865092-4556a000-8c87-11ea-9960-0209aa1a313e.png)


borg info:
![grafik](https://user-images.githubusercontent.com/1151915/80865071-27893b00-8c87-11ea-9c2e-d11c0ca90fdb.png)

Größe: ?

**Comment by m3nu** [comment] 2020-05-02 14:04
Sorry you guys are still unhappy with this behavior. Maybe it helps to understand that Vorta runs different Borg commands and then saves or displays the output in different ways.

While building Vorta, I tried to minimize the number of Borg commands run where possible. That's the reason we don't show updated data all the time. E.g. for old archives we don't get the incremental data after the initial `create` command. That's why we can't show it for newly-added repos.

If I missed an opportunity somewhere to show data that already exists, please submit a pull request for it and we'll add it right away.

If another Borg run is required to display the data or if we can't get the data at all, we most likely can't fix it.

**Comment by Wikinaut** [comment] 2020-05-02 15:20
The problem shows up after having deleted (or pruned) archives in the "stack". There shouldn't be a stale entry, or entry with missing data when the repo is still present (with one archive, as shown).

**Comment by m3nu** [comment] 2020-05-03 01:07
What you describe may happen, if you created a new archive outside of Vorta and then pruned everything else. The new archive would show up after pruning. We currently don't overwrite archives with the same ID, for which size data was saved before.

If you can still reproduce this as a bug, just open a Pull Request here and we'll quickly merge it.

I'll close this one for now, since it's too far off-topic.

**Closed by m3nu** 2020-05-03 01:07 UTC
Labels: status:wontfix
