### ISSUE TITLE
Allow entering the path of local share

### ISSUE THREAD

**Issue by kabaga** [borgbase/vorta#534] opened 2020-06-29 11:14 UTC
**Is your feature request related to a problem? Please describe.**
The issue is #529 

**Describe the solution you'd like**
Allow the user to type in the absolute path of the local share in the Repository URL field. 

**Describe alternatives you've considered**
n/a

**Comment by m3nu** [comment] 2020-08-03 04:37
Duplicate of #529

**Closed by m3nu** 2020-08-03 04:37 UTC
Labels: status:duplicate
