### ISSUE TITLE
on GNOME "add folder" dialog does not work

### ISSUE THREAD

**Issue by FlorianLudwig** [borgbase/vorta#372] opened 2019-10-20 15:18 UTC
**Describe the bug**
"Add folder" dialog behaves like a file-selection dialog, not a folder-selection dialog.

**To Reproduce**
1. Go to 'Sources'
2. Click on 'Add Folder'
3. Select a folder
4. Click on "Open"

Selection dialog stays open and shows folder contents.

**Desktop (please complete the following information):**
Fedora 30
GNOME with wayland
vorta v0.6.23, installed via flatpak

**Comment by Hofer-Julian** [comment] 2019-10-20 15:25
Unfortunately I cannot reproduce this behaviour and I have the exact same setup...

**Comment by FlorianLudwig** [comment] 2019-10-20 15:55
@Hofer-Julian that's really strange.  Any ideas what differences could exist in the setup?

```
$ flatpak list |grep borg
Vorta	com.borgbase.Vorta	v0.6.23	stable	flathub	system
``

**Comment by Hofer-Julian** [comment] 2019-10-20 21:26
File Chooser is one of the situations where the app breaks out of the sandbox, so it stills makes sense to assume that it is specific to your setup.

Unfortunately, I don't know where the problem might be. For now I'd advise you to install Vorta via pip.

**Comment by rubonabo** [comment] 2019-12-16 05:20
Hi, I am facing exactly the same issue:
Does installation via pip, as you suggest, solve the problem???
Thank you for your help

Desktop (please complete the following information):
Pop-OS 19.10 (based on Ubuntu 19.10)
GNOME with wayland
vorta v0.6.23, installed via flatpak

**Comment by Hofer-Julian** [comment] 2019-12-16 09:59
I think I can reproduce this issue now.
It seems to only when Vorta is installed while GNOME + Wayland is running.
I couldn't reproduce it on PCs where at some point Vorta has been installed under X11, even after uninstalling and installing it again running Wayland.

Until this is fixed, the only option is to either use X11 or install Vorta via pip.

**Comment by Hofer-Julian** [comment] 2019-12-16 10:06
@rubonabo and @FlorianLudwig did you experience other problems on Wayland?
Inside the virtual machine with Ubuntu 18.04 and Wayland I had weird window problems, but not sure if that was because of the virtual machine...

**Comment by Hofer-Julian** [comment] 2019-12-17 08:49
I tried a workaround and it works on my virtual machine.

Please try to install `flatpak install --user https://dl.flathub.org/build-repo/12069/com.borgbase.Vorta.flatpakref` and report if the problem is solved.

**Comment by FlorianLudwig** [comment] 2019-12-17 14:37
@Hofer-Julian I had no issues with wayland - I am running vorta from source with wayland just fine. My issue seemed to be only form the flatpack sandbox.

**Comment by Hofer-Julian** [comment] 2019-12-17 14:40
Yes, the combination of Flatpak and Wayland is the problem

**Comment by rubonabo** [comment] 2019-12-18 12:00
Hi,
Thank you Julian for your workaround for the Flatpak installation. I tried it and worked!
I also tried the Source installation and it also worked.
For the Flatpak installation, there is nevertheless a annoying warning:
Warning: org.freedesktop.Platform.openh264 not installed
And it is really not installed! But It seems there is no consequence on Vorta... as it does not use video codec...
Another question: Is there a better way to make a command 'vorta' than creating an alias 'vorta' in either way of installing Vorta?
Thank you very much for your help

**Comment by Hofer-Julian** [comment] 2019-12-19 21:12
> Hi,
> Thank you Julian for your workaround for the Flatpak installation. I tried it and worked!
> I also tried the Source installation and it also worked.

Great, could you please try if` flatpak install --user https://dl.flathub.org/build-repo/12192/com.borgbase.Vorta.flatpakref` works as well?

> For the Flatpak installation, there is nevertheless a annoying warning:
> Warning: org.freedesktop.Platform.openh264 not installed
> And it is really not installed! But It seems there is no consequence on Vorta... as it does not use video codec...

I also got this error on Ubuntu, not sure where it comes from...
> Another question: Is there a better way to make a command 'vorta' than creating an alias 'vorta' in either way of installing Vorta?

Not sure what you are asking.

**Comment by Hofer-Julian** [comment] 2020-03-29 21:20
This should be fixed with the latest version

**Closed by Hofer-Julian** 2020-03-29 21:20 UTC

**Comment by deafmute1** [comment] 2020-12-15 05:33
Just got this same issue on x11 KDE (using the KDE picker) from the latest version of vorta (vorta 0.7.1-3)  installed via the AUR (regular package). Same issues when grabbing the package from pip.

**Comment by samuel-w** [comment] 2020-12-15 08:02
That is https://github.com/borgbase/vorta/issues/693
