### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by daPhipz** [borgbase/vorta#1102] opened 2021-11-08 02:12 UTC
Vorta told me to post this here, so here I am xD
I am using the Flatpak build v0.8.0 with borg v1.1.15 on Kubuntu 21.10.

I didn't do anything special when the error occurred. Vorta was running in the background and did a scheduled backup that finished successfully (at least there are no return codes >0 in the logs from the time when the error message popped up.

I am creating a backup manually right now, will report back if it failed.

This is the error message I got:

```
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/views/schedule_tab.py", line 135, in populate_from_profile
    self.populate_wifi()
  File "/app/lib/python3.7/site-packages/vorta/views/schedule_tab.py", line 144, in populate_wifi
    for wifi in get_sorted_wifis(self.profile()):
  File "/app/lib/python3.7/site-packages/vorta/utils.py", line 304, in get_sorted_wifis
    db_wifi.save()
  File "/app/lib/python3.7/site-packages/playhouse/signals.py", line 71, in save
    ret = super(Model, self).save(*args, **kwargs)
  File "/app/lib/python3.7/site-packages/peewee.py", line 6355, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/app/lib/python3.7/site-packages/peewee.py", line 1812, in inner
    return method(self, database, *args, **kwargs)
  File "/app/lib/python3.7/site-packages/peewee.py", line 1883, in execute
    return self._execute(database)
  File "/app/lib/python3.7/site-packages/peewee.py", line 2360, in _execute
    cursor = database.execute(self)
  File "/app/lib/python3.7/site-packages/peewee.py", line 3018, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/app/lib/python3.7/site-packages/peewee.py", line 3012, in execute_sql
    self.commit()
  File "/app/lib/python3.7/site-packages/peewee.py", line 2783, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/app/lib/python3.7/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/app/lib/python3.7/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked
```

**Comment by m3nu** [comment] 2021-11-08 05:12
Thanks for reporting. Duplicate of #1081. Will be addressed soon.

**Closed by m3nu** 2021-11-08 05:12 UTC

**Comment by daPhipz** [comment] 2021-11-08 10:27
Thanks for the quick response! Keep it up, you rock 🚀
