### ISSUE TITLE
Quota update maybe requires relinking

### ISSUE THREAD

**Issue by akvadrako** [borgbase/vorta#223] opened 2019-03-04 12:31 UTC
**Describe the bug**
I was testing the trial on BorgBase and didn't have enough space, so I purchased a subscription. According to the Web UI, there was no longer a 5GB limit. However, even after quitting Vorta and restarting, it failed to backup because it said the quota was exceeded.

After deleting the repo and creating a new one, then re-linking it worked.

**To Reproduce**
1. Use trial BorgBase account
2. Link to account (with Vorta)
3. Do backup and exceed quota
4. Upgrade account
5. Try to do another backup; the old quota still applies

**Desktop (please complete the following information):**
 - OS: Mac 10.14

**Additional context**
```
2019-03-04 13:03:20,780 - vorta.borg.borg_thread - INFO - Running command borg create --list --info --log-json --json --filter=AM -C lz4 --exclude-from /var/folders/5r/4jcntcq5755bd28zzzmbwlxw0000gn/T/tmpxel3exae ze53xppz@ze53xppz.repo.borgbase.com:repo::Orac.local-default-2019-03-04T13:03:20 /Users/dev
2019-03-04 13:03:22,630 - vorta.borg.borg_thread - INFO - Remote: Storage quota: 275.50 MB out of 5.00 GB used.
2019-03-04 13:07:43,239 - vorta.borg.borg_thread - WARNING - /Users/dev/Library/Application Support/CallHistoryDB: scandir: [Errno 1] Operation not permitted: '/Users/dev/Library/Application Support/CallHistoryDB'
2019-03-04 13:07:43,241 - vorta.borg.borg_thread - WARNING - /Users/dev/Library/Application Support/CallHistoryTransactions: scandir: [Errno 1] Operation not permitted: '/Users/dev/Library/Application Support/CallHistoryTransactions'
2019-03-04 13:13:23,002 - vorta.borg.borg_thread - ERROR - The storage quota (5.00 GB) has been exceeded (5.00 GB). Try deleting some archives.
2019-03-04 13:18:17,373 - vorta.i18n - DEBUG - Loading translation failed for ['C'].
2019-03-04 13:18:17,408 - apscheduler.scheduler - INFO - Scheduler started
2019-03-04 13:19:14,861 - vorta.borg.borg_thread - INFO - Running command /var/folders/5r/4jcntcq5755bd28zzzmbwlxw0000gn/T/_MEILdg5Mu/bin/borg create --list --info --log-json --json --filter=AM -C lz4 --exclude-from /var/folders/5r/4jcntcq5755bd28zzzmbwlxw0000gn/T/tmpse9j2uju ze53xppz@ze53xppz.repo.borgbase.com:repo::Orac.local-default-2019-03-04T13:19:14 /Users/dev
2019-03-04 13:19:17,163 - vorta.borg.borg_thread - INFO - Remote: Storage quota: 275.50 MB out of 5.00 GB used.
```

**Comment by m3nu** [comment] 2019-03-04 12:53
The account quota is refreshed after the credit card transaction is confirmed. I would expect it to take maybe 5 to 15s. Maybe you were too quick or had a quota set on the repo itself. In that case the quota will stay in place even after upgrading (but you can remove it any time of course).

I'll close this since it's unrelated to Vorta itself. If there is any issue with BorgBase, just reply to an email  and I'll reply there.

**Closed by m3nu** 2019-03-04 12:53 UTC
