### ISSUE TITLE
System tray menu not contiguous to icon 

### ISSUE THREAD

**Issue by geckolinux** [borgbase/vorta#398] opened 2020-01-18 17:13 UTC
Hi there, I'm running Vorta 0.6.23 on openSUSE Tumbleweed (rolling) with the latest Plasma / KDE everything. When Vorta is launched, the system tray context menu appears where you would expect, next to the tray icon. But the next time the context menu is used, it looks like this (clipped screenshot of the bottom-right corner of my desktop):

![Screenshot_20200118_120902](https://user-images.githubusercontent.com/2692138/72667628-e167de80-39eb-11ea-9cd2-78b7fafbd704.png)

**Comment by Hofer-Julian** [comment] 2020-01-18 18:37
Sure that this is not an KDE bug? (especially since you use the bleeding edge version?)

**Comment by geckolinux** [comment] 2020-01-19 04:11
Hi there, thanks for the reply. I definitely can't rule out a KDE bug, but it's not bleeding edge, it's the latest stable release. And Vorta is the only app with this bug, you can see that I have lots of other items in the system tray that have normal right-click menu behavior.

**Comment by m3nu** [comment] 2020-06-02 00:22
Does it still happen using Qt 5.14? I can't reproduce it on KDE plasma on Debian Testing.

**Comment by geckolinux** [comment] 2020-06-02 00:43
Yep, this is with Qt 5.14.1 and Vorta 0.6.26:

![Screenshot_20200601_194204](https://user-images.githubusercontent.com/2692138/83467661-39a1f900-a440-11ea-929d-a4256ca94ac6.png)

**Comment by m3nu** [comment] 2020-06-02 00:58
Just saw this as well. It happens due to another text window with just the app name popping up first and the tray menu goes above it. I think this is a feature of the said desktop and we can't do much to change it here.

So I'm closing this now. If someone is aware of a fix we can do here in Vorta, please let us know.

**Closed by m3nu** 2020-06-02 00:58 UTC
Labels: os:linux, status:not-reproducable

**Comment by Goddard** [comment] 2022-07-16 15:53
my vorta icon isn't showing up.

**Comment by real-yfprojects** [comment] 2022-07-16 19:08
@Goddard I think your issue is not related to this one. Please open a new bug report.
