### ISSUE TITLE
FUSE error

### ISSUE THREAD

**Issue by lawzeus** [borgbase/vorta#740] opened 2020-12-06 20:54 UTC
**Describe the bug**
Remotes are not mounting on my Macbook. 
although i have already installed fuse 4.04

**To Reproduce**
1. Go to 'archive'
2. Click on 'mount'
3. Scroll down to ''
4. See error -2020-12-07 02:19:44,831 - vorta.borg.borg_thread - ERROR - borg mount not available: loading FUSE support failed [ImportError: No module named 'llfuse']

**Desktop (please complete the following information):**
- OS:
- Vorta version:0.7.1
- Installed from:  github

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
2020-12-07 01:36:22,010 - vorta.borg.borg_thread - ERROR - borg mount not available: loading FUSE support failed [ImportError: No module named 'llfuse']
2020-12-07 02:19:23,170 - vorta.borg.borg_thread - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2020-12-07 02:19:44,257 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg --log-json mount -o umask=0277,uid=501 h1z2f0i8@h1z2f0i8.repo.borgbase.com:repo /Users/aks/m1
2020-12-07 02:19:44,831 - vorta.borg.borg_thread - ERROR - borg mount not available: loading FUSE support failed [ImportError: No module named 'llfuse']

**Comment by samuel-w** [comment] 2020-12-06 21:04
Closing, duplicate of https://github.com/borgbase/vorta/issues/733

**Closed by samuel-w** 2020-12-06 21:04 UTC
