### ISSUE TITLE
Apply changes to schedule without Apply button

### ISSUE THREAD

**Issue by improve-code** [borgbase/vorta#687] opened 2020-10-14 22:46 UTC
**Is your feature request related to a problem? Please describe.**

It can happen that you accidentally overlook or forget to click on the apply button after changing the schedule. There is no reminder whether to apply the changed schedule settings. You do not instantly see that the intended change was not successful.

I think reliability is a key feature of a backup program, so it would be preferable to change that.

**Describe the solution you'd like**

I like the two-stage setting changing and would keep it, to avoid to accidentally change settings.

I would welcome
-changing colour of the apply button, when schedule settings were changed
-an information when changing the tab bar or closing the window without applying the change

**Describe alternatives you've considered**

Exceeding just giving a information you could use a pop-up with an dialogue whether to change the settings.
Another solution would be to use a new window for changing the schedule. If it is closed without applying the changed schedule settings it shows a reminder.
Another idea would be to let appear the apply button direct on the right of the setting, which was intended to change.

**Comment by m3nu** [comment] 2020-10-15 01:18
The color is decided by Qt. We don't put red buttons or something. 😄

We could apply the settings whenever they change. This means re-adding the job in the background.

**Comment by samuel-w** [comment] 2020-10-15 02:14
Closing, duplicate of #343.

**Closed by samuel-w** 2020-10-15 02:14 UTC
Labels: type:enhancement
