### ISSUE TITLE
Unable to extract

### ISSUE THREAD

**Issue by jperseo** [borgbase/vorta#1502] opened 2022-12-02 23:37 UTC
### Description

After a successful backup, I try to extract an archive, and get an error

``` Error: [Errno 2] no such file or directory: '/var/folders/yp/j57fs0sn77cnfwqwwspptr24000dmd/T/tmpmvjyh315' ```

1. I open Vorta, go to archives, select the archive, then click the extract button
2. I enter the browse screen and select the appropriate files/directories, then click the extract button.
3. On the next screen, I select location, then click open.
4. I get the error on the next screen.

OS Info: MacOS 12.6.1
Installed from brew
vorta: 0.8.9 (auto_updates)
borgbackup: stable 1.2.2 (bottled)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

MacOS 12.6.1

### Version of Vorta

0.8.9 

### What did you install Vorta with?

Homebrew

### Version of Borg

1.2.2 

### Logs

```pytb
022-12-02 16:28:55,398 - vorta.borg.borg_job - INFO - Running command /usr/local/bin/borg extract --list --info --log-json /Volumes/jperseo/jperseo/Backup::squall-2022-12-02-160719 --patterns-from /var/folders/yp/j57fs0sn77vcnfwqwspptr24000dmd/T/tmpmvjyh3l5
2022-12-02 16:28:55,592 - vorta.borg.borg_job - WARNING - Error: [Errno 2] No such file or directory: '/var/folders/yp/j57fs0sn77vcnfwqwspptr24000dmd/T/tmpmvjyh3l5'
2022-12-02 16:28:55,730 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2022-12-02 16:28:55,730 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2022-12-02 16:28:55,740 - vorta.scheduler - DEBUG - Scheduler for profile 1 is disabled.
```

**Comment by real-yfprojects** [comment] 2022-12-03 06:48
Duplicate of #1488.

**Closed by real-yfprojects** 2022-12-03 06:48 UTC
Labels: status:duplicate
