### ISSUE TITLE
UI hanging when cancelling a running backup

### ISSUE THREAD

**Issue by marco44** [borgbase/vorta#332] opened 2019-07-21 15:41 UTC
Start a backup manually, then cancel it. The UI freezes, and the borg process is defunct (zombie, not waited by the parent process)

This occurs on archlinux, using 0.6.21

Please tell me if you need logs.

Regards

**Comment by marco44** [comment] 2019-07-21 15:54
The hang is not happening all the time. The borg defunct process is though

**Comment by Hofer-Julian** [comment] 2019-07-21 16:54
Unfortunately, the cancel-function is quite buggy.

Good to have this issue noted here.

**Comment by markusdd** [comment] 2019-09-04 12:05
Thanks for redirecting here, I was not good enough at searching obviously.

Is it clear where the problem comes from? Is it a Vorta or borg problem?

**Comment by Hofer-Julian** [comment] 2019-09-04 12:07
Should be a Vorta problem

**Comment by m3nu** [comment] 2019-09-07 03:38
Just saw this issue myself. Don't remember ever seeing it before. Will investigate. Maybe it was introduced with a recent change.

**Comment by Plastix** [comment] 2019-10-02 02:46
I'm able to reproduce this on Mac OS 10.14.3.

**Comment by m3nu** [comment] 2019-10-10 04:11
Just tried to debug this and can't reproduce it any more. (after merging a few PRs over the last days)

**Comment by MatanRubin** [comment] 2019-11-06 18:18
I'm hitting this issue constantly on macOS 10.14.6 and Vorta 0.6.23.

**Comment by m3nu** [comment] 2019-11-07 00:48
Can't reproduce this in 0.6.23 or the current master. Are those the correct steps?

1. Open Vorta
2. Go to main window
3. Go to *Archives* Tab
4. Click *Refresh*
5. Wait 5 sec
6. Click *Cancel* => UI becomes unresponsive?

**Comment by MatanRubin** [comment] 2019-11-07 15:22
No, I did this:

1. Open Vorta
2. Go to main window
3. Click "Start Backup"
4. Click Cancel => UI becomes unresponsive

**Comment by m3nu** [comment] 2020-03-09 03:20
Just working on this after seeing a few hangs recently. Still not easy to reproduce. Started out by using `SIGINT` instead of `SIGTERM`, which should give Borg the chance to do some cleanup. Maybe it helps.

**Comment by mauromol** [comment] 2020-12-19 19:48
I'm not sure why this is marked as "closed", but the issue still exists and happens quite often in version 0.7.1.

**Comment by m3nu** [comment] 2020-12-20 00:52
Reopened.

**Comment by m3nu** [comment] 2021-01-19 10:49
Related issue: After cancelling a task, buttons in the *Archives* tab don't re-activate.

**Closed** 2021-02-11 06:24 UTC
Labels: priority:high, type:bug
