### ISSUE TITLE
Scheduler overflow when switching to newly created profile

### ISSUE THREAD

**Issue by Elioby** [borgbase/vorta#1259] opened 2022-04-12 12:51 UTC
```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/views/schedule_tab.py", line 92, in on_scheduler_change
    self.app.scheduler.set_timer_for_profile(profile.id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 111, in set_timer_for_profile
    timer.setInterval(int(timer_ms))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

**To Reproduce**
1. Create a new profile
2. Set the schedule to backup every 1 days
3. Switch to another profile, then back
4. Exception pops up and application freezes

I can reproduce this issue everytime. Seems that setting it to every 24 hours works fine.

**Environment (please complete the following information):**
- OS: Manjaro
- Vorta version: 0.8.3
- Installed from: pip3

**Comment by delfino-nunez** [comment] 2022-04-13 03:24
Can't reproduce on KDE/Ubuntu


https://user-images.githubusercontent.com/770967/163093920-3afce370-c550-4484-ad17-a2052d3259e9.mp4

**Comment by delfino-nunez** [comment] 2022-04-13 04:06
Can't reproduce.
Installed Manjaro and Vorta from pip3, KDE
Linux virtualbox 5.15.28-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:57 UTC 2022 x86_64 GNU/Linux

https://user-images.githubusercontent.com/770967/163098071-8d74b42d-19fa-4e02-a000-99e2d7373ed1.mp4

**Comment by real-yfprojects** [comment] 2022-04-13 05:44
Can you provide the complete logs @Elioby?

**Comment by Chris4477** [comment] 2022-04-16 07:47
Hello,

Sorry for my english i'm french. Im under Manjaro with vorta 0.8.3
Same for me with an existing profile. I can reproduce with a new one also, when "weeks" is choose for scheduling.
Switch to another profile and come back : 

2022-04-16 09:35:43,232 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 09:35:43,234 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-21 00:00:00
2022-04-16 09:35:43,234 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/views/schedule_tab.py", line 92, in on_scheduler_change
    self.app.scheduler.set_timer_for_profile(profile.id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 111, in set_timer_for_profile
    timer.setInterval(int(timer_ms))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
2022-04-16 09:36:56,472 - vorta.i18n - DEBUG - Loading translation succeeded for ['fr', 'fr-FR', 'fr-Latn-FR'].
2022-04-16 09:36:56,653 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.

I choose "1 weeks" when i wrote the profile and when i come back, i see "5 weeks" registered.

**Comment by Chris4477** [comment] 2022-04-16 08:06
I deleted my "default" profile, and now i can access to the one with "1 weeks"

2022-04-16 09:57:52,387 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 09:57:52,387 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-21 00:00:00
2022-04-16 09:57:52,388 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/views/schedule_tab.py", line 92, in on_scheduler_change
    self.app.scheduler.set_timer_for_profile(profile.id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 111, in set_timer_for_profile
    timer.setInterval(int(timer_ms))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
2022-04-16 09:58:06,849 - vorta.i18n - DEBUG - Loading translation succeeded for ['fr', 'fr-FR', 'fr-Latn-FR'].
2022-04-16 09:58:07,055 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2022-04-16 09:58:07,143 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2022-04-16 09:58:07,143 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2022-04-16 09:58:07,160 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2022-04-16 09:58:07,536 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2022-04-16 09:58:07,536 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-04-16 09:58:07,536 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2022-04-16 09:58:07,539 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 09:58:07,540 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-23 00:00:00
2022-04-16 09:58:14,836 - vorta.keyring.abc - DEBUG - Only available on macOS
2022-04-16 09:58:14,869 - asyncio - DEBUG - Using selector: EpollSelector
2022-04-16 09:58:14,871 - vorta.borg.borg_job - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2022-04-16 09:58:14,874 - asyncio - DEBUG - Using selector: EpollSelector
2022-04-16 09:58:14,878 - root - DEBUG - Found 1 passwords matching repo URL.

If i import my "default", the issue come back on the other one

2022-04-16 10:02:34,933 - vorta.scheduler - INFO - Setting timer for profile 1
2022-04-16 10:02:34,934 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:02:34,942 - vorta.scheduler - INFO - Setting timer for profile 1
2022-04-16 10:02:34,943 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:02:38,931 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:02:38,932 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-21 00:00:00
2022-04-16 10:02:38,932 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/views/schedule_tab.py", line 92, in on_scheduler_change
    self.app.scheduler.set_timer_for_profile(profile.id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 111, in set_timer_for_profile
    timer.setInterval(int(timer_ms))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
2022-04-16 10:03:26,539 - vorta.i18n - DEBUG - Loading translation succeeded for ['fr', 'fr-FR', 'fr-Latn-FR'].
2022-04-16 10:03:26,735 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2022-04-16 10:03:26,839 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2022-04-16 10:03:26,839 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2022-04-16 10:03:26,848 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg --version
2022-04-16 10:03:27,183 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2022-04-16 10:03:27,184 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2022-04-16 10:03:27,184 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-04-16 10:03:27,189 - vorta.scheduler - INFO - Setting timer for profile 1
2022-04-16 10:03:27,191 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:03:27,194 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:03:27,195 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-23 00:00:00
2022-04-16 10:03:32,576 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:03:32,577 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-21 00:00:00
2022-04-16 10:03:32,577 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/views/schedule_tab.py", line 92, in on_scheduler_change
    self.app.scheduler.set_timer_for_profile(profile.id)
  File "/usr/lib/python3.10/site-packages/vorta/scheduler.py", line 111, in set_timer_for_profile
    timer.setInterval(int(timer_ms))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
2022-04-16 10:03:46,423 - vorta.i18n - DEBUG - Loading translation succeeded for ['fr', 'fr-FR', 'fr-Latn-FR'].
2022-04-16 10:03:46,623 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.

**Comment by Chris4477** [comment] 2022-04-16 08:28
I deleted my profile 1, create a new one (profile 3) and no more problem.
I can switch to the existing one with 1 weeks (profile 2) scheduling and the 1 days scheduling (profile 3)

2022-04-16 10:18:45,979 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2022-04-16 10:18:45,991 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:18:45,993 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-23 00:00:00
2022-04-16 10:18:45,997 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:18:46,000 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:23:12,107 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:23:12,108 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:23:12,118 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:23:12,119 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:23:14,512 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:23:14,513 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-07 00:00:00
2022-04-16 10:23:14,524 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:23:14,525 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-23 00:00:00
2022-04-16 10:23:19,047 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:23:19,048 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:23:19,058 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:23:19,059 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:23:20,559 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:23:20,561 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-07 00:00:00
2022-04-16 10:23:20,584 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:23:20,585 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-23 00:00:00
2022-04-16 10:24:28,980 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:24:28,981 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:24:28,990 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:24:28,991 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:24:34,297 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:24:34,298 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-07 00:00:00
2022-04-16 10:24:34,306 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:24:34,307 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-23 00:00:00
2022-04-16 10:24:43,600 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:24:43,600 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:24:43,609 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:24:43,610 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:24:55,242 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:24:55,243 - vorta.scheduler - DEBUG - Scheduling next run for 2022-05-07 00:00:00
2022-04-16 10:24:55,253 - vorta.scheduler - INFO - Setting timer for profile 2
2022-04-16 10:24:55,254 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-23 00:00:00
2022-04-16 10:24:56,886 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:24:56,887 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00
2022-04-16 10:24:56,896 - vorta.scheduler - INFO - Setting timer for profile 3
2022-04-16 10:24:56,897 - vorta.scheduler - DEBUG - Scheduling next run for 2022-04-17 06:42:00

**Comment by real-yfprojects** [comment] 2022-04-16 08:40
If you schedule for 5 weeks version 0.8.3 will always have this error. This will be fixed in the next release. Though the initial post reports this error for a schedule of 1 day which shouldn't happen.

> I choose "1 weeks" when i wrote the profile and when i come back, i see "5 weeks" registered.

This is weird. If you import this profile, do you see 5 weeks in the schedule tab or 1 week?

**Comment by Chris4477** [comment] 2022-04-16 09:02
I can't answer, i don't have anymore the profile 1, i deleted all files and created a new one with same characteristics.
And now all works fine. I can't reproduce anymore.

**Comment by real-yfprojects** [comment] 2022-05-15 08:08
Closing since this is a bug of the old scheduler that isn't used any more.

**Closed by real-yfprojects** 2022-05-15 08:08 UTC
Labels: status:needs details, status:not-reproducible
