### ISSUE TITLE
[Severe bug] Profile / Directory issue: Removing a directory from list does not always work - but removed from other profiles!

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#425] opened 2020-03-29 23:18 UTC
* Vorta 0.6.24
* Borg 1.1.10

I just noticed that I could not remove that directory (or another one, when I used another one for testing).

1. I added three directories: /a, /b, and /work
2. I removed /work
3. I run a backup and noticed, that files also from /work where put into the backup.
4. I aborted the backup because I did not want to have /work files included.
5. I noticed, that /work was shown again (see screenshot after having removed all three directories).

Every time when I removed that item, it reappeared when switching to another and then back to that profile. It appears not only an issue of the GUI - the directory was also part of a backup, even when the string was not shown in the list.

![grafik](https://user-images.githubusercontent.com/1151915/77863547-8b04f080-7223-11ea-9adf-0f63ebd6a968.png)

**Comment by Wikinaut** [comment] 2020-03-29 23:21
Update: apparently, removing /work from one profile also has changed my other profiles!

**Comment by Wikinaut** [comment] 2020-03-29 23:45
After killing Vorta and restarting it, this problem was not noticed again.

**Comment by m3nu** [comment] 2020-05-28 03:20
I'll try to reproduce this and close it if I can't. Let me know if this is still an issue.

**Comment by m3nu** [comment] 2020-05-28 04:31
Couldn't reproduce this. Let me know if it happens again or the steps to reproduce changed.

**Closed by m3nu** 2020-05-28 04:31 UTC
