### ISSUE TITLE
mount caused scheduled jobs not to run

### ISSUE THREAD

**Issue by poleguy** [borgbase/vorta#413] opened 2020-03-09 12:44 UTC
**Describe the bug**
I ran mount and restored some files from the mount using a diff tool. I then forgot to unmount. I have a schedule set to run every three hours. A couple days later I noticed an error message in vorta... 

"Failed to create/acquire the lock /misc/seagate_ext/borg/lock (timeout)."

and I noticed that the scheduled jobs had not run. The nonce file in the backup directory had not been touched, and a lock.roster file pointing to a uid of the following process was stuck there.

 /usr/bin/python3.6 /usr/bin/borg --log-json mount -o umask=0277,uid=1000 /misc/seagate_ext/borg::dualie-default-2020-03-06T12:42:00 /tmp/restore

I then ran unmount from vorta, and although it shows three more recent backups in the Archives tab, the data was seemingly not actually backed up, and after that the scheduled backups didn't seem to run at all.

It seems that the mount command blocks the schedule indefinitely, and the UI doesn't go red, so it's a relatively silent failure. That's a very bad type of failure for a backup scheduler. I would recommend removing the mount feature rather than have it implemented in a blocking manner. "The show must go on..." A convenience feature like mount is much less important than the core backup schedule.

**To Reproduce**
I have not attempted again, as I'm waiting to see if the backups will automatically resume at the next scheduled time. I will come back and fill this in later.

**Desktop (please complete the following information):**
Centos 7

**Additional context**

[vorta.log.zip](https://github.com/borgbase/vorta/files/4306607/vorta.log.zip)

**Comment by m3nu** [comment] 2020-03-09 14:36
I would imagine that the repo is locked by Borg while it's mounted. So it's a feature, not a bug.

Have you tried doing backups from the CLI or manually from Vorta while a repo is mounted?

**Comment by m3nu** [comment] 2020-06-02 00:21
I'm closing this, since it's a feature of Borg to lock the repo while it's accessed by `borg mount`.

**Closed by m3nu** 2020-06-02 00:21 UTC
Labels: status:on hold
