### ISSUE TITLE
borg mount not available: loading FUSE support failed

### ISSUE THREAD

**Issue by pin00b** [borgbase/vorta#735] opened 2020-12-04 18:27 UTC
**Describe the bug**
Trying to mount an archive from a given repo fails, ERROR: 
borg mount not available: loading FUSE support failed (ImportError: dlopen(/Applications/Vorta.app/Resources/borg-
dir/llfuse.cpython-37m-darwin.so,2): Library not loaded: @loader _path/libosxfuse.2.dylib
Referenced from:
/Applications/Vorta.app/Contents/Resources/borg-dir/llfuse.cpython-37m-darwin.so
Reason:
no suitable image found
Did find:
file system relative paths not allowed in hardened programs

**Desktop:**
- OS: macOS 11.0.1
- Vorta version: 0.7.1, Borg: 1.1.13
- Installed from: DMG/binary
- FUSE: 4.0.4

If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
--> 
2020-12-04 17:21:18,174 - vorta.borg.borg_thread - ERROR - borg mount not available: loading FUSE support failed [ImportError: dlopen(/Applications/Vorta.app/Contents/Resources/borg-dir/llfuse.cpython-37m-darwin.so, 2): Library not loaded: @loader_path/libosxfuse.2.dylib
  Referenced from: /Applications/Vorta.app/Contents/Resources/borg-dir/llfuse.cpython-37m-darwin.so
  Reason: no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs]

Any help greatly appreciated! Thx!

**Comment by samuel-w** [comment] 2020-12-04 18:33
I believe this is a duplicate of https://github.com/borgbase/vorta/issues/733.

**Comment by pin00b** [comment] 2020-12-04 18:37
> I believe this is a duplicate of #733.
Similar, but not identical, since in my case it states the library not to be loaded, in #733 the error is the following:
[ImportError: No module named 'llfuse']

**Comment by m3nu** [comment] 2020-12-05 01:31
FUSE support was recently removed from Homebrew/macOS. We now maintain a custom Tap for it:

https://github.com/borgbackup/homebrew-tap

So most likely we won't include Borg in future Vorta releases, since it got too complex.

**Comment by pin00b** [comment] 2020-12-05 16:35
> FUSE support was recently removed from Homebrew/macOS. We now maintain a custom Tap for it:
> 
> https://github.com/borgbackup/homebrew-tap
> 
> So most likely we won't include Borg in future Vorta releases, since it got too complex to include FUSE. Too sensitive to different FUSE versions.

Maybe I am too stupid to understand it properly: I installed both Vorta and FUSE via DMG and .pkg respectively. Should I better install both via Homebrew and use FUSE from the tap you support? - Did you plan to remove FUSE support from Vorta in the future? Because Vorta without Borg doesn't make any sense at all! - What would a possibility to mount archives or even repos look like then?

**Comment by m3nu** [comment] 2020-12-06 00:38
If you want FUSE support, you need to install Borg via PyPi or our Tap above. The Tap is rather new and not documented yet.

The official Homebrew Borg doesn't support FUSE any more and the built-in version only works with specific FUSE versions.

We don't plan on removing FUSE support, but we do have to follow developments upstream.

**Comment by dnszero** [comment] 2020-12-28 19:34
In the Vorta GUI (after installing via DMG), the Archives tab still has a link to go download and install FUSE.  ...which is what I did before getting the same error as pin00b and landing here.

Just a reminder to change that message/link for future updates.

**Comment by m3nu** [comment] 2020-12-29 00:10
There are many changes to macFUSE at the moment. We need to wait how it plays our, also in relation to macOS arm64.

**Comment by m3nu** [comment] 2020-12-29 00:24
Generally best to follow the install instructions on the website and use Homebrew. We recently added a Borg tap with working FUSE support: https://vorta.borgbase.com/install/macos/

**Comment by arnonel** [comment] 2021-01-06 11:13
Followed instructions above and still get error: "No suitable image found" and "file system relative paths not allowed in hardened programs"

**Closed** 2021-02-15 07:29 UTC
Labels: os:macos, type:question
