### ISSUE TITLE
Vorta should remember the compression type settings again

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1498] opened 2022-11-24 16:10 UTC
After each restart of Vorta the compression type is reset to LZ4.
No matter what I choose before.

Vorta 0.8.9
Borg 1.2.0
Fedora Flathub Selection

**Comment by real-yfprojects** [comment] 2022-11-24 17:05
Duplicate of #1495.

**Closed by real-yfprojects** 2022-11-24 17:05 UTC
Labels: status:duplicate

**Comment by real-yfprojects** [comment] 2022-11-25 13:29
This is just a GUI (display) bug that doesn't affect the backups. While the compression set are correctly saved and used, it isn't shown correctly after restart.

**Comment by sudwhiwdh** [comment] 2022-12-25 15:49
@real-yfprojects Thanks, had searched for it and found no issue.
And also thanks for https://github.com/borgbase/vorta/pull/1499!
