### ISSUE TITLE
Pass quoted "Extra Borg Arguments" correctly

### ISSUE THREAD

**Issue by kettbi** [borgbase/vorta#453] opened 2020-04-27 15:40 UTC
**Describe the bug**
Hi,  
  
I try to use Vorta for my home backup to a raspberry with a custom ssh port.  
  
When I try to init a new repo for this backup it doesn't work.
In the "Extra Borg Argument" option, I tied to set --rsh "ssh -p 4826" or --rsh="ssh -p 4826" as described in Borg [documentation](https://borgbackup.readthedocs.io/en/stable/man_intro.html?highlight=rsh).
  
I also try to set BORG_RSH environement variable (works using borg in a terminal but not with Vorta)
  
So, I manually init the repo from the raspberry and tried to use it in Vorta but same issue.

This Raspberry is used by 4 servers to handle their backcup via borgmatic and works as well.

**To Reproduce**
1. set a custom ssh port to a ssh server 
2. try to use vorta to create a repo to this server

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3

**Additional context**

```
2020-04-27 17:23:08,721 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-04-27 17:23:08,722 - asyncio - DEBUG - Using selector: EpollSelector
2020-04-27 17:23:08,729 - root - DEBUG - Found 0 passwords matching repo URL.
2020-04-27 17:23:08,730 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2020-04-27 17:23:08,742 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg info --rsh=ssh -p 4826 --info --json --log-json laran@192.168.0.250:/media/usb2/mint_alw
2020-04-27 17:23:08,931 - vorta.borg.borg_thread - WARNING - usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug]
2020-04-27 17:23:08,932 - vorta.borg.borg_thread - WARNING - [--debug-topic TOPIC] [-p] [--log-json] [--lock-wait SECONDS]
2020-04-27 17:23:08,932 - vorta.borg.borg_thread - WARNING - [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
2020-04-27 17:23:08,932 - vorta.borg.borg_thread - WARNING - [--remote-ratelimit RATE] [--consider-part-files]
2020-04-27 17:23:08,932 - vorta.borg.borg_thread - WARNING - [--debug-profile FILE]
2020-04-27 17:23:08,932 - vorta.borg.borg_thread - WARNING - <command> ...
2020-04-27 17:23:08,933 - vorta.borg.borg_thread - WARNING - borg: error: unrecognized arguments: laran@192.168.0.250:/media/usb2/mint_alw
```

```
2020-04-27 17:29:08,185 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-04-27 17:29:08,186 - asyncio - DEBUG - Using selector: EpollSelector
2020-04-27 17:29:08,193 - root - DEBUG - Found 0 passwords matching repo URL.
2020-04-27 17:29:08,193 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2020-04-27 17:29:08,202 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg info --info --json --log-json laran@192.168.0.250:/media/usb2/mint_alw
2020-04-27 17:29:08,456 - vorta.borg.borg_thread - WARNING - Remote: ssh: connect to host 192.168.0.250 port 22: Connection refused
2020-04-27 17:29:08,457 - vorta.borg.borg_thread - ERROR - Connection closed by remote host. Is borg working on the server?
```
any hints?
thanks

**Comment by m3nu** [comment] 2020-04-27 16:12
Quotes are missing. Have you tried single quotes? Quotes may go missing, when passing them to Borg CLI.

`Running command /usr/bin/borg info --rsh=ssh -p 4826 --info --json`

**Comment by kettbi** [comment] 2020-04-28 11:33
I just try with single quotes but it doesn't appear in log too : 

```
2020-04-28 13:30:36,659 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-04-28 13:30:36,660 - asyncio - DEBUG - Using selector: EpollSelector
2020-04-28 13:30:36,667 - root - DEBUG - Found 0 passwords matching repo URL.
2020-04-28 13:30:36,668 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2020-04-28 13:30:36,685 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg info --rsh=ssh -p 4826 --info --json --log-json laran@192.168.0.250:/media/usb2/mint_alw
2020-04-28 13:30:36,867 - vorta.borg.borg_thread - WARNING - usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug]
2020-04-28 13:30:36,868 - vorta.borg.borg_thread - WARNING - [--debug-topic TOPIC] [-p] [--log-json] [--lock-wait SECONDS]
2020-04-28 13:30:36,868 - vorta.borg.borg_thread - WARNING - [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
2020-04-28 13:30:36,868 - vorta.borg.borg_thread - WARNING - [--remote-ratelimit RATE] [--consider-part-files]
2020-04-28 13:30:36,869 - vorta.borg.borg_thread - WARNING - [--debug-profile FILE]
2020-04-28 13:30:36,870 - vorta.borg.borg_thread - WARNING - <command> ...
2020-04-28 13:30:36,871 - vorta.borg.borg_thread - WARNING - borg: error: unrecognized arguments: laran@192.168.0.250:/media/usb2/mint_alw

```

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment] 2020-04-29 16:21
Can you put the port number in the repo definition instead of extra parameter?

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment] 2020-04-29 16:24
Looks like this is when the extra parameter functionality was added:
https://github.com/borgbase/vorta/commit/79b5847460a45c1df5e9a2f8d0281626793944ca

**Comment by kettbi** [comment] 2020-04-29 21:20
When I put the port number in the repo definition, it try to connect to port 22 : 

``2020-04-29 23:14:27,356 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-04-29 23:14:27,356 - asyncio - DEBUG - Using selector: EpollSelector
2020-04-29 23:14:27,359 - root - DEBUG - Found 0 passwords matching repo URL.
2020-04-29 23:14:27,359 - vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2020-04-29 23:14:27,364 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg info --info --json --log-json laran@192.168.0.250:/media/usb2/mint_alw --rsh='ssh -p 4826'
2020-04-29 23:14:27,622 - vorta.borg.borg_thread - WARNING - Remote: ssh: connect to host 192.168.0.250 port 22: Connection refused
2020-04-29 23:14:27,623 - vorta.borg.borg_thread - ERROR - Connection closed by remote host. Is borg working on the server?`
```

**Comment by vapaavetehinen** [comment] 2020-05-31 00:31
I can't seem to reproduce this issue after testing it on PopOS 20.04 if I pass --rsh 'ssh -p 4826' or --rsh='ssh -p 4826' it works.

When I set the repo URL to user@127.0.0.1:/some/random/path and sniff the traffic on the localhost interface without passing those borg params I see borg try to communicate over port 22. But when I pass the params it tries to communicate over 4826 as one would expect. This worked for me using both single and double quotes around the ssh -p 4826, and using "=" or " " after --rsh.

The quotes don't show in the log because the log is a concatenation of the cmd array, but as best I understand the arguments are properly getting passed to borg through the invocation of Popen in borg_thread.py.

**Comment by m3nu** [comment] 2020-05-31 12:32
Thanks for trying to reproduce @vapaavetehinen. I also couldn't reproduce it. Uses the other port as expected.

To avoid many open issues, I'll close this now. If you find out more details, feel free to comment here and I'll reopen and look at it again. If you can pinpoint the precise issue, a pull request would be quickest to fix it.

Thanks everyone!

```
2020-05-31 20:30:22,944 - vorta.borg.borg_thread - INFO - Running command /Users/manu/.pyenv/versions/vorta/bin/borg init --rsh=ssh -p 4826 --info --log-json --encryption=none d38a1814@d38a1814.repo.borgbase.com:repo
2020-05-31 20:30:24,712 - vorta.borg.borg_thread - WARNING - Remote: ssh: connect to host d38a1814.repo.borgbase.com port 4826: Connection refused
2020-05-31 20:30:24,724 - vorta.borg.borg_thread - ERROR - Connection closed by remote host. Is borg working on the server?
```

**Closed by m3nu** 2020-05-31 12:32 UTC
Labels: status:not-reproducable
