### ISSUE TITLE
AttributeError: 'QTranslator' object has no attribute 'language' - root - CRITICAL - Uncaught exception

### ISSUE THREAD

**Issue by karanwilson** [borgbase/vorta#1335] opened 2022-05-26 10:32 UTC
2022-05-26 15:49:03,195 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/app/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language'

**Comment by m3nu** [comment] 2022-05-26 10:49
Already fixed in #1316

**Closed by m3nu** 2022-05-26 10:49 UTC

**Comment by karanwilson** [comment] 2022-05-26 14:53
Dear team,

I am new to Python; how do we "Return the global locale" in:-

src/vorta/i18n/__init__.py (get_locale): Return the global locale.

Regards,
Karan

**Comment by real-yfprojects** [comment] 2022-05-26 18:48
> how do we "Return the global locale" in:- src/vorta/i18n/__init__.py (get_locale): Return the global locale. 

I am not sure what your question is exactly. You can have a look at the source code in the given file.
Btw the issue is already fixed so you don't have to try that.

**Comment by internetman420** [comment] 2022-05-27 00:00
Landed on Elementary OS. Cheers again for quick fix and a great piece of software!

**Comment by karanwilson** [comment] 2022-05-27 05:02
thanks a lot for pushing the update to fix this issue; happy to use Vorta!
