### ISSUE TITLE
sqlite3.OperationalError: duplicate column name: schedule_interval_unit

### ISSUE THREAD

**Issue by dpendolino** [borgbase/vorta#1117] opened 2021-11-18 23:11 UTC
Vorta no longer starts, instead the following stacktrace is printed:

```
2021-11-18 18:06:57,544 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: duplicate column name: schedule_interval_unit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.8.0', 'gui_scripts', 'vorta')())
  File "/usr/lib/python3.9/site-packages/vorta/__main__.py", line 54, in main
    init_db(sqlite_db)
  File "/usr/lib/python3.9/site-packages/vorta/store/connection.py", line 43, in init_db
    run_migrations(current_schema, con)
  File "/usr/lib/python3.9/site-packages/vorta/store/migrations.py", line 128, in run_migrations
    _apply_schema_update(
  File "/usr/lib/python3.9/site-packages/vorta/store/migrations.py", line 143, in _apply_schema_update
    migrate(*operations)
  File "/usr/lib/python3.9/site-packages/playhouse/migrate.py", line 886, in migrate
    operation.run()
  File "/usr/lib/python3.9/site-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/usr/lib/python3.9/site-packages/playhouse/migrate.py", line 158, in _handle_result
    self._handle_result(item)
  File "/usr/lib/python3.9/site-packages/playhouse/migrate.py", line 155, in _handle_result
    result.run()
  File "/usr/lib/python3.9/site-packages/playhouse/migrate.py", line 164, in run
    self._handle_result(method(*self.args, **kwargs))
  File "/usr/lib/python3.9/site-packages/playhouse/migrate.py", line 153, in _handle_result
    self.execute(result)
  File "/usr/lib/python3.9/site-packages/playhouse/migrate.py", line 149, in execute
    self.migrator.database.execute(node)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 3173, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 3167, in execute_sql
    self.commit()
  File "/usr/lib/python3.9/site-packages/peewee.py", line 2933, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.9/site-packages/peewee.py", line 3160, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: duplicate column name: schedule_interval_unit
```

**To Reproduce**
1. Launch Vorta from CLI

**Environment (please complete the following information):**
- OS: Arch Linux
- Vorta version: Vorta 0.8.1
- Installed from: AUR
- Borg Version: borg 1.1.17

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

It happens with `vorta` and `vorta-git` from AUR.

**Comment by bastiencyr** [comment] 2021-11-19 00:02
Hello, 
Seems a duplicate of #1114 but this time, you migration was done and the shemaversion has not been updated. 
A solution would be to open the settings database and change version in the schemaversion table to 18.

**Comment by m3nu** [comment] 2021-11-19 13:30
Would be interesting to learn how this situation arises. Generally the migration is quite robust. No idea why it would run twice.

**Comment by dpendolino** [comment] 2021-11-26 20:04
Thanks, @bastiencyr that worked. 

@m3nu agreed, not sure what happened, but I hadn't had any issues prior to this happening.

**Comment by m3nu** [comment] 2021-11-27 11:36
Glad it works now. Closing this.

**Closed by m3nu** 2021-11-27 11:36 UTC
Labels: type:support
