### ISSUE TITLE
Unable to initialize new repository or add existing repository in vorta

### ISSUE THREAD

**Issue by gcolds** [borgbase/vorta#749] opened 2021-01-01 09:27 UTC
**Describe the bug**
I just moved from KDE Neon to Manjaro linux (fresh install).  After installing vorta flatpak I am in unable to add a new repository or existing repository in vorta.  I get stuck at the file dialog after selecting the target location and clicking open (nothing happens when I do).

**To Reproduce**
1. Select Initalized new repository or Add new repository.
2. Click the folder icon to bring up the file dialog.
3. Select a target directory and click open.
4. Upon clicking open, nothing happens.  The file dialog does not go away.

**Desktop (please complete the following information):**
- OS:  Manjaro Linux
- Vorta version: 0.7.1
- Installed from: Flathub and pip and from AUR

**Additional context**
I have install vorta using pip, and the AUR as well with the same results. I have also tried just typing in the target directory path and that just results in a message appearing that says "Please enter a valid repo URL or select a local path." I have reinstalled Manjaro 2 times.  Same result.

Logs below:
2021-01-01 02:50:45,235 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2021-01-01 02:50:45,246 - apscheduler.scheduler - INFO - Scheduler started
2021-01-01 02:50:45,721 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-01-01 02:50:45,800 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version
2021-01-01 03:24:35,579 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2021-01-01 03:24:35,596 - apscheduler.scheduler - INFO - Scheduler started
2021-01-01 03:24:35,752 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-01-01 03:24:35,880 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version
2021-01-01 03:41:26,455 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2021-01-01 03:41:26,466 - apscheduler.scheduler - INFO - Scheduler started
2021-01-01 03:41:26,599 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-01-01 03:41:26,675 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version

**Comment by Hofer-Julian** [comment] 2021-01-01 19:35
Which desktop environment do you use?

**Comment by gcolds** [comment] 2021-01-01 19:47
I'm using KDE Plasma 5.20.4

**Comment by Hofer-Julian** [comment] 2021-01-01 19:50
I wonder if the file chooser of manjaro is broken again. Do you have another (preferably Qt) app installed, where you can check if you can open a directory with it?

**Comment by gcolds** [comment] 2021-01-01 19:55
I've opened stuff with kate, ocular, libreoffice writer.  No issues.

**Comment by Hofer-Julian** [comment] 2021-01-01 19:59
it is important that you open directories not files

**Comment by gcolds** [comment] 2021-01-01 20:03
Yup I'm selecting directories.  I've selected local directories, nfs mounts, directories in my home directory and outside.  I've also tried selecting directories that were on different drives on my system.  No luck.

**Comment by Hofer-Julian** [comment] 2021-01-01 21:39
Okay, this is indeed curious.
Unfortunately, I have no idea where the problem could lie. We had similar problems in the past, but they could always be backtraced to broken packages or updates. 

Let's keep this issue open for now, hopefully someone can reproduce this with more information.

**Comment by samuel-w** [comment] 2021-01-06 00:52
Duplicate of https://github.com/borgbase/vorta/issues/693, closing.

**Closed by samuel-w** 2021-01-06 00:52 UTC
