### ISSUE TITLE
'python3.7 killed by SIGABRT' when extracting ~/.var/app/com.borgbase.Vorta

### ISSUE THREAD

**Issue by aromanelli** [borgbase/vorta#703] opened 2020-11-05 23:38 UTC
**Describe the bug**
When extracing an archive to a new installation via Vorta (not via command line), Vorta UI disappears and Fedora 33 reports a "python3.7 killed by SIGABRT" error.

Once this happens, the list of archives in the repository is shortened, by one (latest is lost) and you need to disconnect and reattach the repository (or do a 'Refresh').

My goal was to restore a backup to a new PC/installation (old one died), and inherit all my previous Vorta settings.  

Most likely Vorta doesn't like its own data being changed while it is currently running, which makes it that the user will always have to remember to exclude the ~/.var/app/com.borgbase.Vorta directory when doing an extract/restore of ~/.var directory.

**To Reproduce**
1. Run Vorta.
2. Go to the 'Archives' tab.
3. Highlight the latest archive.
4. Press the 'Extract' button.
5. Make sure the home/-USER-/.var.app/com.borgbase.Vorta directory is selected for extracting.

**Desktop (please complete the following information):**
- OS: Fedora 33 Workstation
- Vorta version: 0.7.1
- Installed from: Fedora Software (Flatpak)

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

[xxx@localhost ~]$ flatpak info com.borgbase.Vorta

Vorta - Backup client

          ID: com.borgbase.Vorta
         Ref: app/com.borgbase.Vorta/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: v0.7.1
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 54.0 MB
     Runtime: org.kde.Platform/x86_64/5.14
         Sdk: org.kde.Sdk/x86_64/5.14

      Commit: 96a3dd02990a4c03409e3ae06192951b77d4020bfbd3c04a405ab275fdb9c10e
      Parent: 109123847216e7a1a7e7d192f49feb75fb08962a516dad6fe70ea26bae8318ec
     Subject: Add --filesystem=~/.var/app/ to complete home dir (#30) (f301b4dc)
        Date: 2020-09-14 22:49:28 +0000
[xxx@localhost ~]$ python --version
Python 3.9.0

**Comment by samuel-w** [comment] 2020-11-07 07:44
I'm getting this error when I try to extract it. Same thing happens on a non-flatpak.
```
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/borg/borg_thread.py", line 236, in run
    log_entry.save()
  File "/app/lib/python3.7/site-packages/peewee.py", line 6355, in save
    rows = self.update(**field_dict).where(self._pk_expr()).execute()
  File "/app/lib/python3.7/site-packages/peewee.py", line 1812, in inner
    return method(self, database, *args, **kwargs)
  File "/app/lib/python3.7/site-packages/peewee.py", line 1883, in execute
    return self._execute(database)
  File "/app/lib/python3.7/site-packages/peewee.py", line 2360, in _execute
    cursor = database.execute(self)
  File "/app/lib/python3.7/site-packages/peewee.py", line 3018, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/app/lib/python3.7/site-packages/peewee.py", line 3012, in execute_sql
    self.commit()
  File "/app/lib/python3.7/site-packages/peewee.py", line 2783, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/app/lib/python3.7/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/app/lib/python3.7/site-packages/peewee.py", line 3005, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: attempt to write a readonly database
```
We will have to find some way of swapping out the databases

**Comment by m3nu** [comment] 2021-02-15 06:50
> Most likely Vorta doesn't like its own data being changed while it is currently running, which makes it that the user will always have to remember to exclude the ~/.var/app/com.borgbase.Vorta directory when doing an extract/restore of ~/.var directory.

Probably a bad idea to overwrite user data while it's running. To restore a full user account, I'd use another account.

Closing this, since we can't solve it and it's unrelated to the linked PR.

**Closed by m3nu** 2021-02-15 06:50 UTC
Labels: os:linux, priority:medium, type:bug

**Comment by aromanelli** [comment] 2021-02-27 23:11
For what its worth, that kind of response is why Linux doesn't take over on the desktop.

Its not unreasonable for someone to want to restore from a backup and not have to jump through hoops to do so. Windows doesn't require the extra steps that you used to justify closing this ticket.

As a programmer, I would have assumed that it would be easy enough to put a check in to see if its own directory structure was being restored, and to do a "one off" logic based on that, or at the very least just ignore restoring its own directory structure, if you didn't want to handle updating on the fly logic/coding.

**Comment by samuel-w** [comment] 2021-02-27 23:13
Also this issue is related to the linked PR, the cause is extracting the an old settings db over a new settings db.

**Comment by m3nu** [comment] 2021-02-27 23:34
As a programmer you will know that you shouldnt overwrite all files of a user who is currently logged in. Our settings db file will be the least of your problems.

Instead you restore as another user, fix permissions and then log in as the restored user. This is true for every system including macOS, Linux and Windows.

Could still be mentioned in the docs. So to cover different restore scenarios.

**Comment by samuel-w** [comment] 2021-02-27 23:40
Yes, as a programmer. Not as a user.

**Comment by samuel-w** [comment] 2021-02-27 23:54
Also, I sometimes break my database, and its very annoying having to extract it to a different folder and overwrite it.

**Comment by aromanelli** [comment] 2021-02-27 23:56
> As a programmer you will know that you shouldnt overwrite all files of a user who is currently logged in. Our settings db file will be the least of your problems.
> 
> Instead you restore as another user, fix permissions and then log in as the restored user. This is true for every system including macOS, Linux and Windows.
> 
> Could still be mentioned in the docs. So to cover different restore scenarios.

Again, Windows backup/restore handles this just fine.

And at the very least, you could just put a warning dialog when the directory is selected as one to restore.

Just having the app crash is not a valid excuse to close this.
