### ISSUE TITLE
FR: Setting for the new number format used in the size column of the archive tab

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1713] opened 2023-05-19 16:26 UTC
#### The problem

#1595 complained about the sizes being hard to compare because they have different units. So we changed that in #1598. 

Now people complained in https://github.com/borgbase/vorta/issues/1692#issuecomment-1537640610 that the size figures get too big because it selects a too small unit.

#### Requested Solution

It seems like there are people preferring the old way of displaying the size while there are also people liking the new way. So I suggest keeping both ways and adding a setting that allows toggling between them. The setting should be disabled by default. When it's enabled vorta should use the new mode.

#### Implementation Recipe

1. Add a setting that enables the new size format in [get_misc_settings](https://github.com/borgbase/vorta/blob/d7634e87197eaec36e61a46be133f88d8b73ac23/src/vorta/store/settings.py#L7)
2. Implement behaviour of the setting in [ArchiveTab.populate_from_profile](https://github.com/borgbase/vorta/blob/d7634e87197eaec36e61a46be133f88d8b73ac23/src/vorta/views/archive_tab.py#L246)
3. Test the change

**Comment by bigtedde** [comment] 2023-05-19 16:50
@real-yfprojects I can work on implementing this setting

**Comment by bigtedde** [comment] 2023-05-21 18:28
@real-yfprojects Quick question about implementation: Do we want the setting, when toggled, to immediately update the archive tab to show the new units? Or should the archive tab only check the setting at launch (requiring a restart for a change in setting to show)? 

Thanks

**Comment by real-yfprojects** [comment] 2023-05-21 18:50
> Do we want the setting, when toggled, to immediately update the archive tab to show the new units?

That would be goo.

**Comment by bigtedde** [comment] 2023-05-22 18:23
> > Do we want the setting, when toggled, to immediately update the archive tab to show the new units?
> 
> That would be good.

I added the setting in [get_misc_settings](https://github.com/borgbase/vorta/blob/d7634e87197eaec36e61a46be133f88d8b73ac23/src/vorta/store/settings.py#L7), and implementing the behavior in [ArchiveTab.populate_from_profile](https://github.com/borgbase/vorta/blob/d7634e87197eaec36e61a46be133f88d8b73ac23/src/vorta/views/archive_tab.py#L246). The setting works as intended, but changes only take effect after Vorta restarts. 

However, I'm having trouble connecting a change in setting to an immediate refresh of the archive tab. Can you offer any insight on how to connect these actions?

One option I was considering would be to place the option in the Archive tab instead of Misc. Something like a dropdown box for "fixed number format" or "dynamic number format"

**Comment by real-yfprojects** [comment] 2023-05-22 19:19
> One option I was considering would be to place the option in the Archive tab instead of Misc. Something like a dropdown box for \"fixed number format\" or \"dynamic number format\

That shouldn't be needed. Iirc we used peewee hooks/signals in other places to update the GUI whenever a specific seting changed.

**Comment by bigtedde** [comment] 2023-05-22 21:40
Hmm, I'm having trouble finding an example of updating the GUI with a peewee hook/signal to go off of. I found [this](https://github.com/borgbase/vorta/blob/d7634e87197eaec36e61a46be133f88d8b73ac23/src/vorta/store/connection.py#L27) post_save signal in connection.py, but when I try to use this post_save signal in the ArchiveTab class to update update the archive table when the setting gets changed, it does not work.

I believe post_save signals are typically used outside of class methods, and I am a bit stumped on how to update the GUI outside of the ArchiveTab class.

**Comment by bigtedde** [comment] 2023-05-22 22:41
Ignore previous post, I got it working using pyqt signals and will submit a work in progress PR shortly :)

**Comment by bigtedde** [comment] 2023-05-24 00:38
Thanks for linking me to that example. Are there benefits to using peewee hooks/signals over pyqt signals in this situation?

**Comment by real-yfprojects** [comment] 2023-05-24 05:27
> Thanks for linking me to that example. Are there benefits to using peewee hooks/signals over pyqt signals in this situation?

Qt signals are easier to use and more powerful. However directly connecting to the database provides the benefit, that you can change the setting anywhere in the program and the GUI will update itself without requiring that the developer adds extra code to emit the qt signal.

**Comment by bigtedde** [comment] 2023-05-24 20:10
Ah, that makes a lot of sense. I see that PR you linked has not been merged yet - would you prefer I use PtQt signals for now or go ahead and implement the peewee hook in a similar fashion to what daffy did in that PR?

**Comment by real-yfprojects** [comment] 2023-05-30 10:54
The Qt signal is fine. When needed one can change it at anytime.

**Closed** 2023-08-11 11:22 UTC
Labels: type:enhancement, good first issue
