### ISSUE TITLE
Vorta fails to mount archive in Mac OS Big Sur M1 with "Fuse support failed" error

### ISSUE THREAD

**Issue by ankit255** [borgbase/vorta#1000] opened 2021-05-29 14:30 UTC
**Describe the bug**
Vorta fails to mount archive in Mac OS Big Sur M1 with "Fuse support failed" error. It just results in an error *screenshot attached*.
borg mount seems to mount the repository but the archive folders don't open saying "they don't exist"

**To Reproduce**
1. Go to 'Archives'
2. Click on and select any archive
3. Click "Selected Archive" on lower left and select mount following the prompts

**Environment (please complete the following information):**
- OS: Mac OS Big Sur 11.4
- Vorta version: 0.7.5
- Installed from: Homebrew
<img width="781" alt="Screen Shot 2021-05-29 at 7 58 05 PM" src="https://user-images.githubusercontent.com/5544554/120073957-358ed280-c0b8-11eb-96b7-980bfa570b83.png">
[vorta.log](https://github.com/borgbase/vorta/files/6564815/vorta.log)

omebrew

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by m3nu** [comment] 2021-05-30 05:22
You followed the install instructions to get Fuse support?

https://vorta.borgbase.com/install/macos/

**Comment by ankit255** [comment] 2021-05-30 05:24
Yes I followed exact instructions - basically the list of homebrew commands.

If you have some instructions on what to do next, I’m willing to try.

Ankit

**Comment by m3nu** [comment] 2021-05-30 05:31
Based on the screenshot, Vorta is still using the built-in fallback version of Borg and NOT the version with Fuse support you installed via Homebrew. I’d start looking there and finding out why it’s not found or used.

**Comment by ankit255** [comment] 2021-05-30 05:38
So no one will check if this issue exists for them too? My hopes on making it public was to see this.

Otherwise Im afraid there will be no solution if others with the same issue don’t join heads and search for a solution (by just dumping it back on me).

**Comment by ankit255** [comment] 2021-05-30 06:37
What config file etc. tells Vorta to continue "using the built in fallback version of Borg"?

**Comment by ankit255** [comment] 2021-05-30 07:22
Update: I thoroughly uninstalled all the components (macfuse tap, borgbackup with macfuse and vorta and then did a filename search and removed all files/directories containing them).
I then installed them again as per the instructions only to get the exact same issue. I think that instead of marking this as "type:support", it should be marked as a bug because that is what this is! The maintainer seems to not want to call it that for some reason hmmm.

**Comment by ankit255** [comment] 2021-05-30 10:36
Hi Manu,

You’re right - after numerous reinstalls I tried to look at this angle and found that Vorta is using the Borg prepackaged into it (please see screenshot attached).
Could you please guide me how to fix this?

Thanks
Ankit

**Comment by m3nu** [comment] 2021-05-30 15:01
Duplicate of #1001

**Closed by m3nu** 2021-05-30 15:01 UTC
Labels: type:support
