### ISSUE TITLE
Pruning does not work

### ISSUE THREAD

**Issue by daPhipz** [borgbase/vorta#1594] opened 2023-02-16 23:06 UTC
### Description

Whenever I want to prune my repo, it doesn't work - nothing gets deleted, although it should.

Steps to reproduce:
1. Make sure you have pruning rules set up in such a way that something has to be deleted
2. Click on the "prune" buttton
3. A text appears in the status area ("Dünne alte Archive aus..." aka "Pruning in progress...")
4. A text appears in the status area ("Auffrischen der Archive erledigt" aka "Updating of archive list done")

From the times when pruning worked, I know that between these two messages, there should be messages like "Keeping Archive XYZ" or "Pruning Archive XYZ". These do not appear at all.

To confirm that pruning with Vorta doesn't work, I pruned my repo with the `borg` command from the command line - it took way longer to run and did its job flawlessly.

I hope that the attached log is of any use - I started Vorta, ran a prune operation and copied the log here. So only these two actions should be logged here. If you need any other info or need me to try something - just let me know!

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Kubuntu 22.10

### Version of Vorta

0.8.10

### What did you install Vorta with?

Flatpak

### Version of Borg

1.2.3

### Logs

```pytb
2023-02-16 23:46:53,533 - vorta.i18n - DEBUG - Loading translation succeeded for ['de', 'de-DE', 'de-Latn-DE'].
2023-02-16 23:46:53,537 - vorta.scheduler - WARNING - Failed to connect to DBUS interface to detect sleep/resume events
2023-02-16 23:46:53,693 - root - DEBUG - Expected error parsing file in .ssh: id_rsa (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 301, in _decode_key
    curve_name = msg.get_text()
  File "/app/lib/python3.9/site-packages/paramiko/message.py", line 178, in get_text
    return u(self.get_string())
  File "/app/lib/python3.9/site-packages/paramiko/py3compat.py", line 161, in u
    return s.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 126, in __init__
    self._from_private_key_file(filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 278, in _from_private_key_file
    self._decode_key(data)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 314, in _decode_key
    raise SSHException(str(e))
paramiko.ssh_exception.SSHException: 'utf-8' codec can't decode byte 0xe2 in position 1: invalid continuation byte
2023-02-16 23:46:53,694 - root - DEBUG - Expected error parsing file in .ssh: id_rsa (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/ed25519key.py", line 63, in __init__
    signing_key = self._parse_signing_key_data(data, password)
  File "/app/lib/python3.9/site-packages/paramiko/ed25519key.py", line 112, in _parse_signing_key_data
    raise SSHException("Invalid key")
paramiko.ssh_exception.SSHException: Invalid key
2023-02-16 23:46:53,695 - root - DEBUG - Expected error parsing file in .ssh: id_rsa.pub (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/rsakey.py", line 194, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-02-16 23:46:53,695 - root - DEBUG - Expected error parsing file in .ssh: id_rsa.pub (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 126, in __init__
    self._from_private_key_file(filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 277, in _from_private_key_file
    data = self._read_private_key_file("EC", filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-02-16 23:46:53,695 - root - DEBUG - Expected error parsing file in .ssh: id_rsa.pub (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/ed25519key.py", line 58, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-02-16 23:46:53,696 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/rsakey.py", line 194, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-02-16 23:46:53,696 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 126, in __init__
    self._from_private_key_file(filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 277, in _from_private_key_file
    data = self._read_private_key_file("EC", filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-02-16 23:46:53,696 - root - DEBUG - Expected error parsing file in .ssh: known_hosts.old (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/ed25519key.py", line 58, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-02-16 23:46:53,697 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/rsakey.py", line 64, in __init__
    self._from_private_key_file(filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/rsakey.py", line 194, in _from_private_key_file
    data = self._read_private_key_file("RSA", filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid RSA private key file
2023-02-16 23:46:53,697 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 126, in __init__
    self._from_private_key_file(filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/ecdsakey.py", line 277, in _from_private_key_file
    data = self._read_private_key_file("EC", filename, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 322, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid EC private key file
2023-02-16 23:46:53,698 - root - DEBUG - Expected error parsing file in .ssh: known_hosts (You can safely ignore this)
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/utils.py", line 195, in get_private_keys
    parsed_key = key_format.from_private_key_file(key_file)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 249, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/app/lib/python3.9/site-packages/paramiko/ed25519key.py", line 58, in __init__
    pkformat, data = self._read_private_key("OPENSSH", f)
  File "/app/lib/python3.9/site-packages/paramiko/pkey.py", line 340, in _read_private_key
    raise SSHException("not a valid {} private key file".format(tag))
paramiko.ssh_exception.SSHException: not a valid OPENSSH private key file
2023-02-16 23:46:53,730 - vorta.views.source_tab - DEBUG - Added item number 0 from 1
2023-02-16 23:46:53,896 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2023-02-16 23:46:53,977 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2023-02-16 23:46:53,977 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2023-02-16 23:46:54,004 - vorta.borg.borg_job - INFO - Running command /app/bin/borg --version
2023-02-16 23:46:54,655 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2023-02-16 23:46:54,658 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2023-02-16 23:46:54,658 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2023-02-16 23:46:54,677 - vorta.scheduler - INFO - Setting timer for profile 1
2023-02-16 23:46:54,683 - vorta.scheduler - DEBUG - Scheduling next run for 2023-02-17 00:04:04.525132
2023-02-16 23:48:48,578 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-02-16 23:48:48,628 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-02-16 23:48:48,628 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-02-16 23:48:48,632 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo ssh://pi@192.168.178.30/home/ubuntu/mnt/Backup/borg/
2023-02-16 23:48:48,644 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-02-16 23:48:48,644 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-02-16 23:48:48,681 - vorta.borg.borg_job - INFO - Running command /app/bin/borg prune --list --info --log-json --keep-hourly 3 --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 0 -a sh:Desktop* ssh://pi@192.168.178.30/home/ubuntu/mnt/Backup/borg/
2023-02-16 23:48:58,576 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-02-16 23:48:58,585 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2023-02-16 23:48:58,586 - vorta.scheduler - INFO - Setting timer for profile 1
2023-02-16 23:48:58,589 - vorta.scheduler - DEBUG - Scheduling next run for 2023-02-17 00:04:04.525132
2023-02-16 23:48:58,832 - vorta.keyring.abc - DEBUG - Only available on macOS
2023-02-16 23:48:58,834 - vorta.keyring.abc - DEBUG - Using VortaKWallet5Keyring
2023-02-16 23:48:58,834 - vorta.borg.borg_job - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.
2023-02-16 23:48:58,837 - vorta.keyring.kwallet - DEBUG - Retrieved password for repo ssh://pi@192.168.178.30/home/ubuntu/mnt/Backup/borg/
2023-02-16 23:48:58,845 - vorta.borg.jobs_manager - DEBUG - Add job for site 1
2023-02-16 23:48:58,845 - vorta.borg.jobs_manager - DEBUG - Start job on site: 1
2023-02-16 23:48:58,876 - vorta.borg.borg_job - INFO - Running command /app/bin/borg list --info --log-json --json ssh://pi@192.168.178.30/home/ubuntu/mnt/Backup/borg/
2023-02-16 23:49:05,304 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 1
2023-02-16 23:49:05,309 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: 1
2023-02-16 23:49:05,314 - vorta.scheduler - INFO - Setting timer for profile 1
2023-02-16 23:49:05,319 - vorta.scheduler - DEBUG - Scheduling next run for 2023-02-17 00:04:04.525132
```

**Comment by m3nu** [comment] 2023-02-17 10:16
Likely duplicate of https://github.com/borgbase/vorta/pull/1565

**Comment by daPhipz** [comment] 2023-02-17 11:29
I guess so. Sorry, Shame on me for not checking the closed issues thoroughly :see_no_evil:
Am I right in assuming that this will be fixed in the next Flatpak release, since the patch is already merged into `master`?

**Comment by m3nu** [comment] 2023-02-17 11:39
Yes, will be released with the next version.

**Closed by m3nu** 2023-02-17 11:39 UTC
Labels: status:duplicate
