### ISSUE TITLE
Move Vorta backups to new computer

### ISSUE THREAD

**Issue by smartm0use** [borgbase/vorta#679] opened 2020-10-05 21:26 UTC
Hello,
I have installed Vorta on my new computer with Ubuntu 20.04 and I copied to it Vorta settings folder and .ssh folder from my old computer.
Now on my new computer I have the list of my repositories and I can use my SSH keys.

But when I try to mount backups from archives I get the following error:

**Error - passphrase supplied in BORG_PASSPHRASE, by BORG_PASSCOMMAND or via BORG_PASSPHRASE_FD is incorrect.**

I have already tried to use `borg key export` on old pc and `borg key import` on new one, but nothing changed.

- OS: Ubuntu 20.04
- Vorta version: 0.7.1
- Borg version: 1.1.11-5
- Installed from: pip

**Comment by samuel-w** [comment] 2020-10-06 00:03
Try unlinking and adding the repository. Its probably caused by the password not transferring correctly.

Is the repository in the same directory as before?

**Comment by m3nu** [comment] 2020-10-06 00:27
For Linux the passphrase is saved to the Keyring when it's available. Have you migrated your keyring to the new computer?

If not re-adding the repo will fix it, as Samuel says.

**Comment by smartm0use** [comment] 2020-10-06 20:27
Unlinking and linking again the repository does the trick. Thank you!

For the next times, what is the right way to do that?

**Comment by samuel-w** [comment] 2020-10-06 21:59
Are you using a password manager such as gnome-keyring or keepassxc? That might be the problem, because otherwise it should be just copying and pasting it over.

**Comment by smartm0use** [comment] 2020-10-06 22:05
No, I'm not using any password manager.

**Comment by samuel-w** [comment] 2020-10-06 23:20
The password is stored in the settings if there is no password manager, so it should copy over. I have no idea why it would not.

The message will be more clear with #550, to this:
```
Your repo passphrase was stored in a password manager which is no longer available
Try unlinking and re-adding your repo.
```

**Closed by samuel-w** 2020-10-06 23:20 UTC
Labels: type:support

**Comment by smartm0use** [comment] 2021-01-18 11:42
I have encountered the same problem and I confirm that unlinking and re-adding the repo does the trick.
Thank you.
