### ISSUE TITLE
Translation: Confirm deletion dialog text not translated

### ISSUE THREAD

**Issue by delfino-nunez** [borgbase/vorta#1224] opened 2022-03-19 07:20 UTC
**Describe the bug**
The dialog "Confirm deletion" title and dialog text is not translated even when translation exists in transifex and ts files.
The dialog buttons get translated correctly.

**To Reproduce**
1. Set Language
2. Click on tab 'Archive'
3. Select one archive file
4. Click on "Selected Archive"
5. Click on "Delete" option
6. The "Confirm deletion" dialog is displayed with text in English.

![Confirm-deletion-dialog-fr](https://user-images.githubusercontent.com/770967/159111693-171a132d-761f-427a-9ae7-3f1970cb80dc.png)

![Confirm-deletion-dialog-es](https://user-images.githubusercontent.com/770967/159111698-132149d4-fca8-4e4b-9845-f12b1a742e26.png)

**Environment (please complete the following information):**
- OS: Linux 5.13.0-35-generic # 40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Vorta version: 0.8.3
- Installed from: GitHub

**Additional context**
Translations exists in transifex and ts files.

**Comment by m3nu** [comment] 2022-03-19 12:43
Duplicate of #1223

**Closed by m3nu** 2022-03-19 12:43 UTC

**Comment by real-yfprojects** [comment] 2022-03-19 13:18
One will have to go over all GUI strings and fix the use of `trans_late` and `translate`, because this is the problem of #1223 and #1224 as well as the missing use of either of them.
