### ISSUE TITLE
FR: Allow filtering files by file size

### ISSUE THREAD

**Issue by 3v1n0** [borgbase/vorta#1635] opened 2023-03-08 18:37 UTC
#### The problem

I have various big files in the paths I want to backup that I may do not want to backup, so it would be nice to be able to filter them out

#### Requested Solution

Add an option to filter files by their size

**Comment by real-yfprojects** [comment] 2023-03-08 19:11
Duplicate of borgbackup/borg#4102

**Closed by real-yfprojects** 2023-03-08 19:11 UTC
Labels: type:enhancement
