### ISSUE TITLE
extracting

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#431] opened 2020-04-02 08:33 UTC
To become familiar with Vorta, I decided 
1. to use my external hard disk as source. 
2. to use my external hard drive to save the backup Repository. 
This should prevent me from accidentally overwriting any files when I extract something.

So I made a backup of 
/media/Konto/Seagate 2TB-2/Vorta Quellen/

After i did the following extracting experiments:

**Experiment 1:**
I press the extract button, then in the browser I browse to "Vorta Quellen". To be concrete I marked the folder "Vorta Quellen" and pressed "open".

My hope was, that now the backup will override the source with the backuped files.
But the backup was restored in
/media/Konto/Seagate 2TB-2/Vorta Quellen/media/Konto/Seagate 2TB-2/Vorta Quellen/
This is the wrong place.
My expectation was: /media/Konto/Seagate 2TB-2/Vorta Quellen/

**Expereiment 2:**
I press the extract button, then in the browser I change to root and navigate to the media folder.
To be concrete I marked the folder "media" in my root and pressed "open".

My hope was, that now the backup will override the source with the backuped files.
But I didn't find the location where the backup has been restored. Where now is my restore?
I also did not get any message like something "You can now find your restored data in folder XXX". Also I did not get any error like: "It was not possible to restore your data in the desired folder."

**Question:**
How can I restore my backup of 
/media/Konto/Seagate 2TB-2/Vorta Quellen/
in 
/media/Konto/Seagate 2TB-2/Vorta Quellen/

I have no idea.
Would appreciate some hints. Thank you.

**Comment by m3nu** [comment] 2020-04-02 08:41
I believe Borg extracts the full path to the selected (or CWD) unless you give the `--strip-components` option. We would need to implement that first in Vorta. Feel free to add a pull request or suggest how it could look like in the UI.

**Comment by m3nu** [comment] 2020-05-28 03:16
Closing this as duplicate of #441

**Closed by m3nu** 2020-05-28 03:16 UTC

**Comment by Golddouble** [comment] 2020-07-20 07:21
> **Question:**
> How can I restore my backup of
> /media/Konto/Seagate 2TB-2/Vorta Quellen/
> in
> /media/Konto/Seagate 2TB-2/Vorta Quellen/
> 
> I have no idea.
> Would appreciate some hints. Thank you.


Answer: Just extract to "/" .
