### ISSUE TITLE
borg version does not support zstd

### ISSUE THREAD

**Issue by silverfoxdoc** [borgbase/vorta#2139] opened 2024-11-17 17:37 UTC
### Description

since upgrading to vorta 0.10.x I keep getting repeated warnings that my borg version does not support zstd compression which I am using to backup. 

I am using hombrew to manage packages and have tried reinstalling ztsd and borgbackup/tap/borgbackup-fuse prior to reinstalling vorta. 

Looking at settings / about in vorta, when at it automatically loads at startup of MacOS, it initially gives the borg path as: 
`/Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe`

but if I close and then reopen vorta it finds my local install of borg: `/usr/loca/bin/borg`

Either way, I get a message on startup of vorta everytime stating "Your current Borg version does not support ZStd compression" 

It also seem to fail to perform scheduled backups but I think that might be a separate issue but there are quite a lot of errors in the log file and not entirely sure why they are happening. 

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

macos 15.1

### Version of Vorta

0.10.1

### What did you install Vorta with?

Homebrew

### Version of Borg

1.4.0

### Logs

```pytb
2024-11-17 17:15:20,584 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2024-11-17 17:15:20,584 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
2024-11-17 17:15:23,443 - vorta.i18n - DEBUG - Loading translation succeeded for ['en-GB', 'en-Latn-GB'].
2024-11-17 17:15:23,447 - vorta.scheduler - WARNING - Failed to connect to DBUS interface to detect sleep/resume events
2024-11-17 17:15:23,629 - vorta.views.source_tab - DEBUG - Added item number 0 from 1
2024-11-17 17:15:23,900 - root - INFO - Using DarwinNetworkStatus NetworkStatusMonitor implementation.
2024-11-17 17:15:23,949 - vorta.scheduler - INFO - Setting timer for profile 1
2024-11-17 17:15:23,950 - vorta.scheduler - DEBUG - Catching up by running job for Default (1)
2024-11-17 17:15:23,951 - vorta.scheduler - INFO - Starting background backup for Default
2024-11-17 17:15:23,952 - vorta.notifications - DEBUG - success notifications suppressed
2024-11-17 17:15:23,968 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2024-11-17 17:15:23,969 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2024-11-17 17:15:23,969 - vorta.borg.borg_job - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2024-11-17 17:15:23,979 - vorta.keyring.darwin - DEBUG - Retrieved password for repo ssh://xxxxxxx@xxxxxxxxx.repo.borgbase.com/./repo
2024-11-17 17:15:24,020 - root - DEBUG - Command ipconfig getpacket en0 failed
2024-11-17 17:15:24,029 - root - DEBUG - Command ipconfig getpacket bridge0 failed
2024-11-17 17:15:24,048 - root - DEBUG - Command ipconfig getpacket en2 failed
2024-11-17 17:15:24,059 - root - DEBUG - Command ipconfig getpacket en3 failed
2024-11-17 17:15:24,069 - root - DEBUG - Command ipconfig getpacket en4 failed
2024-11-17 17:15:24,078 - root - DEBUG - Command ipconfig getpacket en5 failed
2024-11-17 17:15:24,078 - vorta.scheduler - ERROR - Conditions for backup not met. Aborting.
2024-11-17 17:15:24,078 - vorta.scheduler - ERROR - Your current Borg version does not support ZStd compression.
2024-11-17 17:15:24,079 - vorta.notifications - DEBUG - notification not suppressed
2024-11-17 17:15:24,081 - vorta.scheduler - DEBUG - Paused 1 until 2024-11-17 18:15:24
2024-11-17 17:15:24,084 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of timeout until 2024-11-17 18:15:24.
2024-11-17 17:15:24,086 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of timeout until 2024-11-17 18:15:24.
2024-11-17 17:15:24,116 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2024-11-17 17:15:24,117 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2024-11-17 17:15:24,118 - vorta.borg.borg_job - INFO - Running command /usr/local/bin/borg --version
2024-11-17 17:15:24,405 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2024-11-17 17:15:24,406 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default
2024-11-17 17:15:29,060 - vorta.scheduler - DEBUG - Refreshing all scheduler timers
2024-11-17 17:15:29,062 - vorta.scheduler - DEBUG - Nothing scheduled for profile 1 because of timeout until 2024-11-17 18:15:24.
```

**Comment by m3nu** [comment] 2024-11-18 06:12
Likely duplicate of #2129

**Comment by silverfoxdoc** [comment] 2024-11-18 09:43
Thanks I hadn't spotted that issue. 

So if I uncheck 'Run missed backups on startup or wakeup` this does seem to stop the problem of throwing the warning. Howevere it then means if I turn on my computer after the backup was scheduled to happen (18:00) I won't get a back up unfortunately -- I don't keep my computer running 24/7.

I wasn't clear what the solution was from #2129.

Is this related to the earlier message in the log `vorta.scheduler - WARNING - Failed to connect to DBUS interface to detect sleep/resume events` as well?

**Comment by azzydoesgit** [comment] 2024-12-01 20:25
> To address this, we can increase the fallback version of Borg we assume. So the backup won't fail.
> 
> Basically any backup running before this log line will fail: `Running command /usr/local/bin/borg --version` since the Borg version isn't known yet. Any manual backups after the version was detected should be fine.

Why not just schedule `borg --version` to happen sooner? Obviously there should be a good fallback system in case that fails, but why is there a scenario where vorta initiates a backup before knowing what version of borg is currently installed in the first place?

**Closed** 2024-12-05 13:54 UTC
Labels: status:duplicate
