### ISSUE TITLE
"Refreshing snapshots" run's forever for very large repos

### ISSUE THREAD

**Issue by JanSchnacki** [borgbase/vorta#21] opened 2018-11-19 20:39 UTC
I have... a LOT of snapshots (511 of them).

After adding my existing repository Vorta quickly shows size-information (Original Size: 44TB; Deduplicated Size: 162GB; Compressed Size: 88GB).

Also, the progress bar changes into the "flowing" orange and the text "Refreshing snapshots.." is shown.

It stays there. I just hit "cancel" after significantly more than one day. I have no idea if it actually did anything. The disks in my NAS weren't active and I'm seeing just about zero network traffic.

I have no idea what's happening or how to show what's currently being done.

**Comment by JanSchnacki** [comment] 2018-11-19 20:39
Oh, and: the Snapshots list is empty.

**Comment by m3nu** [comment] 2018-11-19 23:40
Thanks for the report. Will try to reproduce this and increase the log level to show what's happening if there are no other status updates.

**Comment by m3nu** [comment] 2018-11-20 02:10
Couldn't reproduce this for now on a remote or local repo.

Can you try running `borg list --log-json --json $REPO_URL` directly and see what the output is?

- If `borg` fails to retrieve it, there is not much we can do in Vorta.
- If it works, it should work in Vorta as well. Then I'd try again in the GUI.

**Comment by JanSchnacki** [comment] 2018-11-20 21:40
That command results in 155KB of JSON data.

The repository is password-protected. I know that I could (and did) enter the password when registering the repository, but is it possible, that the password is not entered while trying to refresh the snapshot list?

**Comment by m3nu** [comment] 2018-11-26 14:35
Figured this one out while adding the `extract` subcommand: When reading both `stdout` and `stderr`, they can block each other, which needs to be handled.

**Comment by m3nu** [comment] 2018-11-27 00:41
Yes. We need both for sure.

- stdout: has the result of the command. Like listing of archives or files. Or repo stats.
- stderr: has logging output as json format.

It's already fixed in the `extract`-command I'm working on. Will be ready to merge later today or tomorrow.

**Closed** 2018-11-27 11:33 UTC
Labels: type:bug

**Comment by JanSchnacki** [comment] 2018-11-28 21:13
Thanks for all your work. I'm so sorry that I keep running into problems. I would love to switch to vorta from my hand-grown scripts because I really think it will fit my use case perfectly.

The "run's forever" part is now fixed. Refreshing snapshots will stop after a few moments. Unfortunately I don't get to see any snapshots. I'll open a new ticket for that.
